//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.16 at 02:52:13 PM EST 
//


package com.selman.calcfocus.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomerExtract complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerExtract">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="custome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type4Rec" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="type5Rec" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="type7Rec" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerExtract", propOrder = {
    "custome",
    "type4Rec",
    "type5Rec",
    "type7Rec"
})
public class CustomerExtract {

    @XmlElement(required = true)
    protected String custome;
    @XmlElement(required = true)
    protected List<String> type4Rec;
    protected List<String> type5Rec;
    @XmlElement(required = true)
    protected String type7Rec;

    /**
     * Gets the value of the custome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustome() {
        return custome;
    }

    /**
     * Sets the value of the custome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustome(String value) {
        this.custome = value;
    }

    /**
     * Gets the value of the type4Rec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the type4Rec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getType4Rec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getType4Rec() {
        if (type4Rec == null) {
            type4Rec = new ArrayList<String>();
        }
        return this.type4Rec;
    }

    /**
     * Gets the value of the type5Rec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the type5Rec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getType5Rec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getType5Rec() {
        if (type5Rec == null) {
            type5Rec = new ArrayList<String>();
        }
        return this.type5Rec;
    }

    /**
     * Gets the value of the type7Rec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType7Rec() {
        return type7Rec;
    }

    /**
     * Sets the value of the type7Rec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType7Rec(String value) {
        this.type7Rec = value;
    }

}
