//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.23 at 11:48:47 AM EDT 
//


package com.selman.calcfocus.response;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IllustrationStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IllustrationStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AtIssue"/>
 *     &lt;enumeration value="Inforce"/>
 *     &lt;enumeration value="PreIssue"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IllustrationStatus")
@XmlEnum
public enum IllustrationStatus {

    @XmlEnumValue("AtIssue")
    AT_ISSUE("AtIssue"),
    @XmlEnumValue("Inforce")
    INFORCE("Inforce"),
    @XmlEnumValue("PreIssue")
    PRE_ISSUE("PreIssue");
    private final String value;

    IllustrationStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IllustrationStatus fromValue(String v) {
        for (IllustrationStatus c: IllustrationStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
