//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.23 at 11:48:47 AM EDT 
//


package com.selman.calcfocus.response;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IncomeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IncomeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Salary"/>
 *     &lt;enumeration value="Rental"/>
 *     &lt;enumeration value="SocialSecurity"/>
 *     &lt;enumeration value="Pension"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IncomeType")
@XmlEnum
public enum IncomeType {

    @XmlEnumValue("Salary")
    SALARY("Salary"),
    @XmlEnumValue("Rental")
    RENTAL("Rental"),
    @XmlEnumValue("SocialSecurity")
    SOCIAL_SECURITY("SocialSecurity"),
    @XmlEnumValue("Pension")
    PENSION("Pension"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    IncomeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IncomeType fromValue(String v) {
        for (IncomeType c: IncomeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
