//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.23 at 11:48:47 AM EDT 
//


package com.selman.calcfocus.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InsuranceProposal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsuranceProposal">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="proposalDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="totalDuration" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="levelType" type="{http://xmlns.calcfocus.com/services/calc}InsuranceLevelType" minOccurs="0"/>
 *         &lt;element name="netPresentCost" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="productOfferReason" type="{http://xmlns.calcfocus.com/services/calc}ProductOfferReason" minOccurs="0"/>
 *         &lt;element name="guaranteedSimplifiedOfferType" type="{http://xmlns.calcfocus.com/services/calc}GuaranteedSimplifiedOfferType" minOccurs="0"/>
 *         &lt;element name="simplifiedIssueDeterminationRule" type="{http://xmlns.calcfocus.com/services/calc}SimplifiedIssueDeterminationRule" minOccurs="0"/>
 *         &lt;element name="endOfYearValues" type="{http://xmlns.calcfocus.com/services/calc}EndOfYearValues" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="policySummary" type="{http://xmlns.calcfocus.com/services/calc}PolicySummary" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsuranceProposal", propOrder = {
    "proposalDescription",
    "totalDuration",
    "levelType",
    "netPresentCost",
    "productOfferReason",
    "guaranteedSimplifiedOfferType",
    "simplifiedIssueDeterminationRule",
    "endOfYearValues",
    "policySummary"
})
public class InsuranceProposal {

    protected String proposalDescription;
    protected Integer totalDuration;
    protected InsuranceLevelType levelType;
    protected Double netPresentCost;
    protected ProductOfferReason productOfferReason;
    protected GuaranteedSimplifiedOfferType guaranteedSimplifiedOfferType;
    protected SimplifiedIssueDeterminationRule simplifiedIssueDeterminationRule;
    protected List<EndOfYearValues> endOfYearValues;
    @XmlElement(required = true)
    protected List<PolicySummary> policySummary;

    /**
     * Gets the value of the proposalDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProposalDescription() {
        return proposalDescription;
    }

    /**
     * Sets the value of the proposalDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProposalDescription(String value) {
        this.proposalDescription = value;
    }

    /**
     * Gets the value of the totalDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalDuration() {
        return totalDuration;
    }

    /**
     * Sets the value of the totalDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalDuration(Integer value) {
        this.totalDuration = value;
    }

    /**
     * Gets the value of the levelType property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceLevelType }
     *     
     */
    public InsuranceLevelType getLevelType() {
        return levelType;
    }

    /**
     * Sets the value of the levelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceLevelType }
     *     
     */
    public void setLevelType(InsuranceLevelType value) {
        this.levelType = value;
    }

    /**
     * Gets the value of the netPresentCost property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getNetPresentCost() {
        return netPresentCost;
    }

    /**
     * Sets the value of the netPresentCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNetPresentCost(Double value) {
        this.netPresentCost = value;
    }

    /**
     * Gets the value of the productOfferReason property.
     * 
     * @return
     *     possible object is
     *     {@link ProductOfferReason }
     *     
     */
    public ProductOfferReason getProductOfferReason() {
        return productOfferReason;
    }

    /**
     * Sets the value of the productOfferReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductOfferReason }
     *     
     */
    public void setProductOfferReason(ProductOfferReason value) {
        this.productOfferReason = value;
    }

    /**
     * Gets the value of the guaranteedSimplifiedOfferType property.
     * 
     * @return
     *     possible object is
     *     {@link GuaranteedSimplifiedOfferType }
     *     
     */
    public GuaranteedSimplifiedOfferType getGuaranteedSimplifiedOfferType() {
        return guaranteedSimplifiedOfferType;
    }

    /**
     * Sets the value of the guaranteedSimplifiedOfferType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GuaranteedSimplifiedOfferType }
     *     
     */
    public void setGuaranteedSimplifiedOfferType(GuaranteedSimplifiedOfferType value) {
        this.guaranteedSimplifiedOfferType = value;
    }

    /**
     * Gets the value of the simplifiedIssueDeterminationRule property.
     * 
     * @return
     *     possible object is
     *     {@link SimplifiedIssueDeterminationRule }
     *     
     */
    public SimplifiedIssueDeterminationRule getSimplifiedIssueDeterminationRule() {
        return simplifiedIssueDeterminationRule;
    }

    /**
     * Sets the value of the simplifiedIssueDeterminationRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimplifiedIssueDeterminationRule }
     *     
     */
    public void setSimplifiedIssueDeterminationRule(SimplifiedIssueDeterminationRule value) {
        this.simplifiedIssueDeterminationRule = value;
    }

    /**
     * Gets the value of the endOfYearValues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the endOfYearValues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEndOfYearValues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EndOfYearValues }
     * 
     * 
     */
    public List<EndOfYearValues> getEndOfYearValues() {
        if (endOfYearValues == null) {
            endOfYearValues = new ArrayList<EndOfYearValues>();
        }
        return this.endOfYearValues;
    }

    /**
     * Gets the value of the policySummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the policySummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolicySummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PolicySummary }
     * 
     * 
     */
    public List<PolicySummary> getPolicySummary() {
        if (policySummary == null) {
            policySummary = new ArrayList<PolicySummary>();
        }
        return this.policySummary;
    }

}
