//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.23 at 11:48:47 AM EDT 
//


package com.selman.calcfocus.response;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LifetimeFinancialAdviceMode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LifetimeFinancialAdviceMode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="InsuranceRecommendationOnly"/>
 *     &lt;enumeration value="InsuranceRecommendationOnlyProjectFuture"/>
 *     &lt;enumeration value="RetirementProductsOnlyProjectFuture"/>
 *     &lt;enumeration value="InsuranceRecommendationRetirementProductsProjectFuture"/>
 *     &lt;enumeration value="InvestmentOnlyProjectFuture"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LifetimeFinancialAdviceMode")
@XmlEnum
public enum LifetimeFinancialAdviceMode {

    @XmlEnumValue("InsuranceRecommendationOnly")
    INSURANCE_RECOMMENDATION_ONLY("InsuranceRecommendationOnly"),
    @XmlEnumValue("InsuranceRecommendationOnlyProjectFuture")
    INSURANCE_RECOMMENDATION_ONLY_PROJECT_FUTURE("InsuranceRecommendationOnlyProjectFuture"),
    @XmlEnumValue("RetirementProductsOnlyProjectFuture")
    RETIREMENT_PRODUCTS_ONLY_PROJECT_FUTURE("RetirementProductsOnlyProjectFuture"),
    @XmlEnumValue("InsuranceRecommendationRetirementProductsProjectFuture")
    INSURANCE_RECOMMENDATION_RETIREMENT_PRODUCTS_PROJECT_FUTURE("InsuranceRecommendationRetirementProductsProjectFuture"),
    @XmlEnumValue("InvestmentOnlyProjectFuture")
    INVESTMENT_ONLY_PROJECT_FUTURE("InvestmentOnlyProjectFuture");
    private final String value;

    LifetimeFinancialAdviceMode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LifetimeFinancialAdviceMode fromValue(String v) {
        for (LifetimeFinancialAdviceMode c: LifetimeFinancialAdviceMode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
