//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.16 at 02:52:13 PM EST 
//


package com.selman.calcfocus.response;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PerceptionOfHealth.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PerceptionOfHealth">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="WorseThanPeers"/>
 *     &lt;enumeration value="SameAsPeers"/>
 *     &lt;enumeration value="BetterThanPeers"/>
 *     &lt;enumeration value="Exceptional"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PerceptionOfHealth")
@XmlEnum
public enum PerceptionOfHealth {

    @XmlEnumValue("WorseThanPeers")
    WORSE_THAN_PEERS("WorseThanPeers"),
    @XmlEnumValue("SameAsPeers")
    SAME_AS_PEERS("SameAsPeers"),
    @XmlEnumValue("BetterThanPeers")
    BETTER_THAN_PEERS("BetterThanPeers"),
    @XmlEnumValue("Exceptional")
    EXCEPTIONAL("Exceptional");
    private final String value;

    PerceptionOfHealth(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PerceptionOfHealth fromValue(String v) {
        for (PerceptionOfHealth c: PerceptionOfHealth.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
