//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.23 at 11:48:47 AM EDT 
//


package com.selman.calcfocus.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Premium complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Premium">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://xmlns.calcfocus.com/services/calc}PremiumType"/>
 *         &lt;element name="annual" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="modal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="quarterly" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="semiAnnual" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="monthly" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="biweekly" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="bimonthly" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="weekly" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="ninthly" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="tenthly" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Premium", propOrder = {
    "type",
    "annual",
    "modal",
    "quarterly",
    "semiAnnual",
    "monthly",
    "biweekly",
    "bimonthly",
    "weekly",
    "ninthly",
    "tenthly"
})
public class Premium {

    @XmlElement(required = true)
    protected PremiumType type;
    protected Double annual;
    protected Double modal;
    protected Double quarterly;
    protected Double semiAnnual;
    protected Double monthly;
    protected Double biweekly;
    protected Double bimonthly;
    protected Double weekly;
    protected Double ninthly;
    protected Double tenthly;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link PremiumType }
     *     
     */
    public PremiumType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link PremiumType }
     *     
     */
    public void setType(PremiumType value) {
        this.type = value;
    }

    /**
     * Gets the value of the annual property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAnnual() {
        return annual;
    }

    /**
     * Sets the value of the annual property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAnnual(Double value) {
        this.annual = value;
    }

    /**
     * Gets the value of the modal property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getModal() {
        return modal;
    }

    /**
     * Sets the value of the modal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setModal(Double value) {
        this.modal = value;
    }

    /**
     * Gets the value of the quarterly property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQuarterly() {
        return quarterly;
    }

    /**
     * Sets the value of the quarterly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQuarterly(Double value) {
        this.quarterly = value;
    }

    /**
     * Gets the value of the semiAnnual property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSemiAnnual() {
        return semiAnnual;
    }

    /**
     * Sets the value of the semiAnnual property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSemiAnnual(Double value) {
        this.semiAnnual = value;
    }

    /**
     * Gets the value of the monthly property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMonthly() {
        return monthly;
    }

    /**
     * Sets the value of the monthly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMonthly(Double value) {
        this.monthly = value;
    }

    /**
     * Gets the value of the biweekly property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBiweekly() {
        return biweekly;
    }

    /**
     * Sets the value of the biweekly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBiweekly(Double value) {
        this.biweekly = value;
    }

    /**
     * Gets the value of the bimonthly property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBimonthly() {
        return bimonthly;
    }

    /**
     * Sets the value of the bimonthly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBimonthly(Double value) {
        this.bimonthly = value;
    }

    /**
     * Gets the value of the weekly property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWeekly() {
        return weekly;
    }

    /**
     * Sets the value of the weekly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWeekly(Double value) {
        this.weekly = value;
    }

    /**
     * Gets the value of the ninthly property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getNinthly() {
        return ninthly;
    }

    /**
     * Sets the value of the ninthly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNinthly(Double value) {
        this.ninthly = value;
    }

    /**
     * Gets the value of the tenthly property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTenthly() {
        return tenthly;
    }

    /**
     * Sets the value of the tenthly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTenthly(Double value) {
        this.tenthly = value;
    }

}
