//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.23 at 11:48:47 AM EDT 
//


package com.selman.calcfocus.response;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SolveGoalType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SolveGoalType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Endow"/>
 *     &lt;enumeration value="AccountValue"/>
 *     &lt;enumeration value="CashSurrenderValue"/>
 *     &lt;enumeration value="LoanBalance"/>
 *     &lt;enumeration value="FacePremiumSolve"/>
 *     &lt;enumeration value="MaximumLevelPremium"/>
 *     &lt;enumeration value="MinimumFace"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SolveGoalType")
@XmlEnum
public enum SolveGoalType {

    @XmlEnumValue("Endow")
    ENDOW("Endow"),
    @XmlEnumValue("AccountValue")
    ACCOUNT_VALUE("AccountValue"),
    @XmlEnumValue("CashSurrenderValue")
    CASH_SURRENDER_VALUE("CashSurrenderValue"),
    @XmlEnumValue("LoanBalance")
    LOAN_BALANCE("LoanBalance"),
    @XmlEnumValue("FacePremiumSolve")
    FACE_PREMIUM_SOLVE("FacePremiumSolve"),
    @XmlEnumValue("MaximumLevelPremium")
    MAXIMUM_LEVEL_PREMIUM("MaximumLevelPremium"),
    @XmlEnumValue("MinimumFace")
    MINIMUM_FACE("MinimumFace");
    private final String value;

    SolveGoalType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SolveGoalType fromValue(String v) {
        for (SolveGoalType c: SolveGoalType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
