//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.23 at 11:48:47 AM EDT 
//


package com.selman.calcfocus.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WholeLifeEndOfYearValues complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WholeLifeEndOfYearValues">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="baseDeathBenefit" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="oneYearTermDeathBenefit" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="additionalInsuranceDeathBenefit" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="paidUpInsuranceDeathBenefit" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="reducedPaidUpFaceAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="additionalInsuranceCashValue" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="paidUpInsuranceCashValue" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="dividendsAccumulatingAtInterestCashValue" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="baseDividend" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="additionalInsuranceDividend" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="paidUpInsuranceDividend" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="dividendAppliedToPremiums" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="dividendAppliedToAdditionalInsurance" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="dividendAppliedToOYT" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="dividendAppliedToPaidUpInsurance" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="dividendAppliedToInterestAccumulation" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="dividendAppliedToLoanBalance" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="dividendDisbursedAsCash" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfAnnualPUAPremiums" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumISWLCharges" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumISWLPremium" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumISWLPremiumPaidFromFund" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WholeLifeEndOfYearValues", propOrder = {
    "baseDeathBenefit",
    "oneYearTermDeathBenefit",
    "additionalInsuranceDeathBenefit",
    "paidUpInsuranceDeathBenefit",
    "reducedPaidUpFaceAmount",
    "additionalInsuranceCashValue",
    "paidUpInsuranceCashValue",
    "dividendsAccumulatingAtInterestCashValue",
    "baseDividend",
    "additionalInsuranceDividend",
    "paidUpInsuranceDividend",
    "dividendAppliedToPremiums",
    "dividendAppliedToAdditionalInsurance",
    "dividendAppliedToOYT",
    "dividendAppliedToPaidUpInsurance",
    "dividendAppliedToInterestAccumulation",
    "dividendAppliedToLoanBalance",
    "dividendDisbursedAsCash",
    "sumOfAnnualPUAPremiums",
    "sumISWLCharges",
    "sumISWLPremium",
    "sumISWLPremiumPaidFromFund"
})
public class WholeLifeEndOfYearValues {

    protected Double baseDeathBenefit;
    protected Double oneYearTermDeathBenefit;
    protected Double additionalInsuranceDeathBenefit;
    protected Double paidUpInsuranceDeathBenefit;
    protected Double reducedPaidUpFaceAmount;
    protected Double additionalInsuranceCashValue;
    protected Double paidUpInsuranceCashValue;
    protected Double dividendsAccumulatingAtInterestCashValue;
    protected Double baseDividend;
    protected Double additionalInsuranceDividend;
    protected Double paidUpInsuranceDividend;
    protected Double dividendAppliedToPremiums;
    protected Double dividendAppliedToAdditionalInsurance;
    protected Double dividendAppliedToOYT;
    protected Double dividendAppliedToPaidUpInsurance;
    protected Double dividendAppliedToInterestAccumulation;
    protected Double dividendAppliedToLoanBalance;
    protected Double dividendDisbursedAsCash;
    protected Double sumOfAnnualPUAPremiums;
    protected Double sumISWLCharges;
    protected Double sumISWLPremium;
    protected Double sumISWLPremiumPaidFromFund;

    /**
     * Gets the value of the baseDeathBenefit property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBaseDeathBenefit() {
        return baseDeathBenefit;
    }

    /**
     * Sets the value of the baseDeathBenefit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBaseDeathBenefit(Double value) {
        this.baseDeathBenefit = value;
    }

    /**
     * Gets the value of the oneYearTermDeathBenefit property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getOneYearTermDeathBenefit() {
        return oneYearTermDeathBenefit;
    }

    /**
     * Sets the value of the oneYearTermDeathBenefit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOneYearTermDeathBenefit(Double value) {
        this.oneYearTermDeathBenefit = value;
    }

    /**
     * Gets the value of the additionalInsuranceDeathBenefit property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAdditionalInsuranceDeathBenefit() {
        return additionalInsuranceDeathBenefit;
    }

    /**
     * Sets the value of the additionalInsuranceDeathBenefit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAdditionalInsuranceDeathBenefit(Double value) {
        this.additionalInsuranceDeathBenefit = value;
    }

    /**
     * Gets the value of the paidUpInsuranceDeathBenefit property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPaidUpInsuranceDeathBenefit() {
        return paidUpInsuranceDeathBenefit;
    }

    /**
     * Sets the value of the paidUpInsuranceDeathBenefit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPaidUpInsuranceDeathBenefit(Double value) {
        this.paidUpInsuranceDeathBenefit = value;
    }

    /**
     * Gets the value of the reducedPaidUpFaceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getReducedPaidUpFaceAmount() {
        return reducedPaidUpFaceAmount;
    }

    /**
     * Sets the value of the reducedPaidUpFaceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setReducedPaidUpFaceAmount(Double value) {
        this.reducedPaidUpFaceAmount = value;
    }

    /**
     * Gets the value of the additionalInsuranceCashValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAdditionalInsuranceCashValue() {
        return additionalInsuranceCashValue;
    }

    /**
     * Sets the value of the additionalInsuranceCashValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAdditionalInsuranceCashValue(Double value) {
        this.additionalInsuranceCashValue = value;
    }

    /**
     * Gets the value of the paidUpInsuranceCashValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPaidUpInsuranceCashValue() {
        return paidUpInsuranceCashValue;
    }

    /**
     * Sets the value of the paidUpInsuranceCashValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPaidUpInsuranceCashValue(Double value) {
        this.paidUpInsuranceCashValue = value;
    }

    /**
     * Gets the value of the dividendsAccumulatingAtInterestCashValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDividendsAccumulatingAtInterestCashValue() {
        return dividendsAccumulatingAtInterestCashValue;
    }

    /**
     * Sets the value of the dividendsAccumulatingAtInterestCashValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDividendsAccumulatingAtInterestCashValue(Double value) {
        this.dividendsAccumulatingAtInterestCashValue = value;
    }

    /**
     * Gets the value of the baseDividend property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBaseDividend() {
        return baseDividend;
    }

    /**
     * Sets the value of the baseDividend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBaseDividend(Double value) {
        this.baseDividend = value;
    }

    /**
     * Gets the value of the additionalInsuranceDividend property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAdditionalInsuranceDividend() {
        return additionalInsuranceDividend;
    }

    /**
     * Sets the value of the additionalInsuranceDividend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAdditionalInsuranceDividend(Double value) {
        this.additionalInsuranceDividend = value;
    }

    /**
     * Gets the value of the paidUpInsuranceDividend property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPaidUpInsuranceDividend() {
        return paidUpInsuranceDividend;
    }

    /**
     * Sets the value of the paidUpInsuranceDividend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPaidUpInsuranceDividend(Double value) {
        this.paidUpInsuranceDividend = value;
    }

    /**
     * Gets the value of the dividendAppliedToPremiums property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDividendAppliedToPremiums() {
        return dividendAppliedToPremiums;
    }

    /**
     * Sets the value of the dividendAppliedToPremiums property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDividendAppliedToPremiums(Double value) {
        this.dividendAppliedToPremiums = value;
    }

    /**
     * Gets the value of the dividendAppliedToAdditionalInsurance property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDividendAppliedToAdditionalInsurance() {
        return dividendAppliedToAdditionalInsurance;
    }

    /**
     * Sets the value of the dividendAppliedToAdditionalInsurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDividendAppliedToAdditionalInsurance(Double value) {
        this.dividendAppliedToAdditionalInsurance = value;
    }

    /**
     * Gets the value of the dividendAppliedToOYT property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDividendAppliedToOYT() {
        return dividendAppliedToOYT;
    }

    /**
     * Sets the value of the dividendAppliedToOYT property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDividendAppliedToOYT(Double value) {
        this.dividendAppliedToOYT = value;
    }

    /**
     * Gets the value of the dividendAppliedToPaidUpInsurance property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDividendAppliedToPaidUpInsurance() {
        return dividendAppliedToPaidUpInsurance;
    }

    /**
     * Sets the value of the dividendAppliedToPaidUpInsurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDividendAppliedToPaidUpInsurance(Double value) {
        this.dividendAppliedToPaidUpInsurance = value;
    }

    /**
     * Gets the value of the dividendAppliedToInterestAccumulation property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDividendAppliedToInterestAccumulation() {
        return dividendAppliedToInterestAccumulation;
    }

    /**
     * Sets the value of the dividendAppliedToInterestAccumulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDividendAppliedToInterestAccumulation(Double value) {
        this.dividendAppliedToInterestAccumulation = value;
    }

    /**
     * Gets the value of the dividendAppliedToLoanBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDividendAppliedToLoanBalance() {
        return dividendAppliedToLoanBalance;
    }

    /**
     * Sets the value of the dividendAppliedToLoanBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDividendAppliedToLoanBalance(Double value) {
        this.dividendAppliedToLoanBalance = value;
    }

    /**
     * Gets the value of the dividendDisbursedAsCash property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDividendDisbursedAsCash() {
        return dividendDisbursedAsCash;
    }

    /**
     * Sets the value of the dividendDisbursedAsCash property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDividendDisbursedAsCash(Double value) {
        this.dividendDisbursedAsCash = value;
    }

    /**
     * Gets the value of the sumOfAnnualPUAPremiums property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfAnnualPUAPremiums() {
        return sumOfAnnualPUAPremiums;
    }

    /**
     * Sets the value of the sumOfAnnualPUAPremiums property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfAnnualPUAPremiums(Double value) {
        this.sumOfAnnualPUAPremiums = value;
    }

    /**
     * Gets the value of the sumISWLCharges property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumISWLCharges() {
        return sumISWLCharges;
    }

    /**
     * Sets the value of the sumISWLCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumISWLCharges(Double value) {
        this.sumISWLCharges = value;
    }

    /**
     * Gets the value of the sumISWLPremium property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumISWLPremium() {
        return sumISWLPremium;
    }

    /**
     * Sets the value of the sumISWLPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumISWLPremium(Double value) {
        this.sumISWLPremium = value;
    }

    /**
     * Gets the value of the sumISWLPremiumPaidFromFund property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumISWLPremiumPaidFromFund() {
        return sumISWLPremiumPaidFromFund;
    }

    /**
     * Sets the value of the sumISWLPremiumPaidFromFund property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumISWLPremiumPaidFromFund(Double value) {
        this.sumISWLPremiumPaidFromFund = value;
    }

}
