//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.16 at 02:52:28 PM EST 
//


package com.selman.calcfocus.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnchoredScenario complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnchoredScenario">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="interestAssumption" type="{http://xmlns.calcfocus.com/services/calc}InterestAssumption"/>
 *         &lt;element name="mortalityAssumption" type="{http://xmlns.calcfocus.com/services/calc}MortalityAssumption"/>
 *         &lt;element name="alternateInterestRate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnchoredScenario", propOrder = {
    "interestAssumption",
    "mortalityAssumption",
    "alternateInterestRate"
})
public class AnchoredScenario {

    @XmlElement(required = true)
    protected InterestAssumption interestAssumption;
    @XmlElement(required = true)
    protected MortalityAssumption mortalityAssumption;
    protected Double alternateInterestRate;

    /**
     * Gets the value of the interestAssumption property.
     * 
     * @return
     *     possible object is
     *     {@link InterestAssumption }
     *     
     */
    public InterestAssumption getInterestAssumption() {
        return interestAssumption;
    }

    /**
     * Sets the value of the interestAssumption property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterestAssumption }
     *     
     */
    public void setInterestAssumption(InterestAssumption value) {
        this.interestAssumption = value;
    }

    /**
     * Gets the value of the mortalityAssumption property.
     * 
     * @return
     *     possible object is
     *     {@link MortalityAssumption }
     *     
     */
    public MortalityAssumption getMortalityAssumption() {
        return mortalityAssumption;
    }

    /**
     * Sets the value of the mortalityAssumption property.
     * 
     * @param value
     *     allowed object is
     *     {@link MortalityAssumption }
     *     
     */
    public void setMortalityAssumption(MortalityAssumption value) {
        this.mortalityAssumption = value;
    }

    /**
     * Gets the value of the alternateInterestRate property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAlternateInterestRate() {
        return alternateInterestRate;
    }

    /**
     * Sets the value of the alternateInterestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAlternateInterestRate(Double value) {
        this.alternateInterestRate = value;
    }

}
