//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.23 at 11:48:17 AM EDT 
//


package com.selman.calcfocus.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssetType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AssetType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Savings"/>
 *     &lt;enumeration value="IRA"/>
 *     &lt;enumeration value="RetirementPlan"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AssetType")
@XmlEnum
public enum AssetType {

    @XmlEnumValue("Savings")
    SAVINGS("Savings"),
    IRA("IRA"),
    @XmlEnumValue("RetirementPlan")
    RETIREMENT_PLAN("RetirementPlan"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    AssetType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AssetType fromValue(String v) {
        for (AssetType c: AssetType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
