//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.26 at 10:39:22 PM EDT 
//


package com.selman.calcfocus.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AsyncExtractType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AsyncExtractType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ArcVal"/>
 *     &lt;enumeration value="ConversionUpdate"/>
 *     &lt;enumeration value="Pol40"/>
 *     &lt;enumeration value="Pol42"/>
 *     &lt;enumeration value="Pol44"/>
 *     &lt;enumeration value="Pol46"/>
 *     &lt;enumeration value="Pol50"/>
 *     &lt;enumeration value="Pol56"/>
 *     &lt;enumeration value="Pol60"/>
 *     &lt;enumeration value="Val44_Liens"/>
 *     &lt;enumeration value="Val44_Loans"/>
 *     &lt;enumeration value="Val44_DeathClaims"/>
 *     &lt;enumeration value="Val44_Suspended"/>
 *     &lt;enumeration value="Val44_Suspense"/>
 *     &lt;enumeration value="Val53"/>
 *     &lt;enumeration value="Val63"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AsyncExtractType")
@XmlEnum
public enum AsyncExtractType {

    @XmlEnumValue("ArcVal")
    ARC_VAL("ArcVal"),
    @XmlEnumValue("ConversionUpdate")
    CONVERSION_UPDATE("ConversionUpdate"),
    @XmlEnumValue("Pol40")
    POL_40("Pol40"),
    @XmlEnumValue("Pol42")
    POL_42("Pol42"),
    @XmlEnumValue("Pol44")
    POL_44("Pol44"),
    @XmlEnumValue("Pol46")
    POL_46("Pol46"),
    @XmlEnumValue("Pol50")
    POL_50("Pol50"),
    @XmlEnumValue("Pol56")
    POL_56("Pol56"),
    @XmlEnumValue("Pol60")
    POL_60("Pol60"),
    @XmlEnumValue("Val44_Liens")
    VAL_44_LIENS("Val44_Liens"),
    @XmlEnumValue("Val44_Loans")
    VAL_44_LOANS("Val44_Loans"),
    @XmlEnumValue("Val44_DeathClaims")
    VAL_44_DEATH_CLAIMS("Val44_DeathClaims"),
    @XmlEnumValue("Val44_Suspended")
    VAL_44_SUSPENDED("Val44_Suspended"),
    @XmlEnumValue("Val44_Suspense")
    VAL_44_SUSPENSE("Val44_Suspense"),
    @XmlEnumValue("Val53")
    VAL_53("Val53"),
    @XmlEnumValue("Val63")
    VAL_63("Val63");
    private final String value;

    AsyncExtractType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AsyncExtractType fromValue(String v) {
        for (AsyncExtractType c: AsyncExtractType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
