//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.16 at 02:52:28 PM EST 
//


package com.selman.calcfocus.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AtIssuePolicyFeeRule.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AtIssuePolicyFeeRule">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="Amount"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AtIssuePolicyFeeRule")
@XmlEnum
public enum AtIssuePolicyFeeRule {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Amount")
    AMOUNT("Amount");
    private final String value;

    AtIssuePolicyFeeRule(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AtIssuePolicyFeeRule fromValue(String v) {
        for (AtIssuePolicyFeeRule c: AtIssuePolicyFeeRule.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
