//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.26 at 10:39:22 PM EDT 
//


package com.selman.calcfocus.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://xmlns.calcfocus.com/services/calc}Header" minOccurs="0"/>
 *         &lt;element name="context" type="{http://xmlns.calcfocus.com/services/calc}Context"/>
 *         &lt;element name="policy" type="{http://xmlns.calcfocus.com/services/calc}Policy" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="party" type="{http://xmlns.calcfocus.com/services/calc}Party" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="address" type="{http://xmlns.calcfocus.com/services/calc}Address" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="annualStatementAdminData" type="{http://xmlns.calcfocus.com/services/calc}AnnualStatementAdminData" minOccurs="0"/>
 *         &lt;element name="lifetimeFinancialAdviceProjection" type="{http://xmlns.calcfocus.com/services/calc}LifetimeFinancialAdviceProjection" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "context",
    "policy",
    "party",
    "address",
    "annualStatementAdminData",
    "lifetimeFinancialAdviceProjection"
})
@XmlRootElement(name = "calculateRequest")
public class CalculateRequest {

    protected Header header;
    @XmlElement(required = true)
    protected Context context;
    protected List<Policy> policy;
    protected List<Party> party;
    protected List<Address> address;
    protected AnnualStatementAdminData annualStatementAdminData;
    protected LifetimeFinancialAdviceProjection lifetimeFinancialAdviceProjection;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link Context }
     *     
     */
    public Context getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link Context }
     *     
     */
    public void setContext(Context value) {
        this.context = value;
    }

    /**
     * Gets the value of the policy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the policy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolicy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Policy }
     * 
     * 
     */
    public List<Policy> getPolicy() {
        if (policy == null) {
            policy = new ArrayList<Policy>();
        }
        return this.policy;
    }

    /**
     * Gets the value of the party property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the party property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Party }
     * 
     * 
     */
    public List<Party> getParty() {
        if (party == null) {
            party = new ArrayList<Party>();
        }
        return this.party;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Address }
     * 
     * 
     */
    public List<Address> getAddress() {
        if (address == null) {
            address = new ArrayList<Address>();
        }
        return this.address;
    }

    /**
     * Gets the value of the annualStatementAdminData property.
     * 
     * @return
     *     possible object is
     *     {@link AnnualStatementAdminData }
     *     
     */
    public AnnualStatementAdminData getAnnualStatementAdminData() {
        return annualStatementAdminData;
    }

    /**
     * Sets the value of the annualStatementAdminData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnualStatementAdminData }
     *     
     */
    public void setAnnualStatementAdminData(AnnualStatementAdminData value) {
        this.annualStatementAdminData = value;
    }

    /**
     * Gets the value of the lifetimeFinancialAdviceProjection property.
     * 
     * @return
     *     possible object is
     *     {@link LifetimeFinancialAdviceProjection }
     *     
     */
    public LifetimeFinancialAdviceProjection getLifetimeFinancialAdviceProjection() {
        return lifetimeFinancialAdviceProjection;
    }

    /**
     * Sets the value of the lifetimeFinancialAdviceProjection property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifetimeFinancialAdviceProjection }
     *     
     */
    public void setLifetimeFinancialAdviceProjection(LifetimeFinancialAdviceProjection value) {
        this.lifetimeFinancialAdviceProjection = value;
    }

}
