//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.23 at 11:48:17 AM EDT 
//


package com.selman.calcfocus.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DefinitionOfLifeInsurance.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DefinitionOfLifeInsurance">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="GuidelinePremiumTest"/>
 *     &lt;enumeration value="CashValueAccumulationTest"/>
 *     &lt;enumeration value="PolicyholderElected"/>
 *     &lt;enumeration value="NotApplicable"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DefinitionOfLifeInsurance")
@XmlEnum
public enum DefinitionOfLifeInsurance {

    @XmlEnumValue("GuidelinePremiumTest")
    GUIDELINE_PREMIUM_TEST("GuidelinePremiumTest"),
    @XmlEnumValue("CashValueAccumulationTest")
    CASH_VALUE_ACCUMULATION_TEST("CashValueAccumulationTest"),
    @XmlEnumValue("PolicyholderElected")
    POLICYHOLDER_ELECTED("PolicyholderElected"),
    @XmlEnumValue("NotApplicable")
    NOT_APPLICABLE("NotApplicable");
    private final String value;

    DefinitionOfLifeInsurance(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DefinitionOfLifeInsurance fromValue(String v) {
        for (DefinitionOfLifeInsurance c: DefinitionOfLifeInsurance.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
