//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.23 at 11:48:17 AM EDT 
//


package com.selman.calcfocus.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Income complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Income">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://xmlns.calcfocus.com/services/calc}IncomeType"/>
 *         &lt;element name="startDateType" type="{http://xmlns.calcfocus.com/services/calc}StartDateType"/>
 *         &lt;element name="startAge" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="startYear" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="endDateType" type="{http://xmlns.calcfocus.com/services/calc}EndDateType" minOccurs="0"/>
 *         &lt;element name="endAge" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="endYear" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="bonusAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="commissionAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="familyAmountAfterDeath" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="employmentGUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Income", propOrder = {
    "type",
    "startDateType",
    "startAge",
    "startYear",
    "endDateType",
    "endAge",
    "endYear",
    "amount",
    "bonusAmount",
    "commissionAmount",
    "familyAmountAfterDeath",
    "employmentGUID"
})
public class Income {

    @XmlElement(required = true)
    protected IncomeType type;
    @XmlElement(required = true)
    protected StartDateType startDateType;
    protected Integer startAge;
    protected Integer startYear;
    protected EndDateType endDateType;
    protected Integer endAge;
    protected Integer endYear;
    protected double amount;
    protected Double bonusAmount;
    protected Double commissionAmount;
    protected Double familyAmountAfterDeath;
    protected String employmentGUID;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link IncomeType }
     *     
     */
    public IncomeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncomeType }
     *     
     */
    public void setType(IncomeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the startDateType property.
     * 
     * @return
     *     possible object is
     *     {@link StartDateType }
     *     
     */
    public StartDateType getStartDateType() {
        return startDateType;
    }

    /**
     * Sets the value of the startDateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartDateType }
     *     
     */
    public void setStartDateType(StartDateType value) {
        this.startDateType = value;
    }

    /**
     * Gets the value of the startAge property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStartAge() {
        return startAge;
    }

    /**
     * Sets the value of the startAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStartAge(Integer value) {
        this.startAge = value;
    }

    /**
     * Gets the value of the startYear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStartYear() {
        return startYear;
    }

    /**
     * Sets the value of the startYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStartYear(Integer value) {
        this.startYear = value;
    }

    /**
     * Gets the value of the endDateType property.
     * 
     * @return
     *     possible object is
     *     {@link EndDateType }
     *     
     */
    public EndDateType getEndDateType() {
        return endDateType;
    }

    /**
     * Sets the value of the endDateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndDateType }
     *     
     */
    public void setEndDateType(EndDateType value) {
        this.endDateType = value;
    }

    /**
     * Gets the value of the endAge property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEndAge() {
        return endAge;
    }

    /**
     * Sets the value of the endAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEndAge(Integer value) {
        this.endAge = value;
    }

    /**
     * Gets the value of the endYear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEndYear() {
        return endYear;
    }

    /**
     * Sets the value of the endYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEndYear(Integer value) {
        this.endYear = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public double getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(double value) {
        this.amount = value;
    }

    /**
     * Gets the value of the bonusAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBonusAmount() {
        return bonusAmount;
    }

    /**
     * Sets the value of the bonusAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBonusAmount(Double value) {
        this.bonusAmount = value;
    }

    /**
     * Gets the value of the commissionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCommissionAmount() {
        return commissionAmount;
    }

    /**
     * Sets the value of the commissionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCommissionAmount(Double value) {
        this.commissionAmount = value;
    }

    /**
     * Gets the value of the familyAmountAfterDeath property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFamilyAmountAfterDeath() {
        return familyAmountAfterDeath;
    }

    /**
     * Sets the value of the familyAmountAfterDeath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFamilyAmountAfterDeath(Double value) {
        this.familyAmountAfterDeath = value;
    }

    /**
     * Gets the value of the employmentGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentGUID() {
        return employmentGUID;
    }

    /**
     * Sets the value of the employmentGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentGUID(String value) {
        this.employmentGUID = value;
    }

}
