//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.23 at 11:48:17 AM EDT 
//


package com.selman.calcfocus.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InsuranceLevel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsuranceLevel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://xmlns.calcfocus.com/services/calc}InsuranceLevelType"/>
 *         &lt;element name="bequestPercentage" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="childCareCostPercentage" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="collegeCostPercentage" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="debtPercentage" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="incomeReplacementPercentage" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsuranceLevel", propOrder = {
    "type",
    "bequestPercentage",
    "childCareCostPercentage",
    "collegeCostPercentage",
    "debtPercentage",
    "incomeReplacementPercentage"
})
public class InsuranceLevel {

    @XmlElement(required = true)
    protected InsuranceLevelType type;
    protected Double bequestPercentage;
    protected Double childCareCostPercentage;
    protected Double collegeCostPercentage;
    protected Double debtPercentage;
    protected Double incomeReplacementPercentage;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceLevelType }
     *     
     */
    public InsuranceLevelType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceLevelType }
     *     
     */
    public void setType(InsuranceLevelType value) {
        this.type = value;
    }

    /**
     * Gets the value of the bequestPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBequestPercentage() {
        return bequestPercentage;
    }

    /**
     * Sets the value of the bequestPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBequestPercentage(Double value) {
        this.bequestPercentage = value;
    }

    /**
     * Gets the value of the childCareCostPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getChildCareCostPercentage() {
        return childCareCostPercentage;
    }

    /**
     * Sets the value of the childCareCostPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setChildCareCostPercentage(Double value) {
        this.childCareCostPercentage = value;
    }

    /**
     * Gets the value of the collegeCostPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCollegeCostPercentage() {
        return collegeCostPercentage;
    }

    /**
     * Sets the value of the collegeCostPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCollegeCostPercentage(Double value) {
        this.collegeCostPercentage = value;
    }

    /**
     * Gets the value of the debtPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDebtPercentage() {
        return debtPercentage;
    }

    /**
     * Sets the value of the debtPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDebtPercentage(Double value) {
        this.debtPercentage = value;
    }

    /**
     * Gets the value of the incomeReplacementPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIncomeReplacementPercentage() {
        return incomeReplacementPercentage;
    }

    /**
     * Sets the value of the incomeReplacementPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIncomeReplacementPercentage(Double value) {
        this.incomeReplacementPercentage = value;
    }

}
