//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.23 at 11:48:17 AM EDT 
//


package com.selman.calcfocus.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InsuranceChoicePreferences complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsuranceChoicePreferences">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="underwritingClass" type="{http://xmlns.calcfocus.com/services/calc}UnderwritingClass" minOccurs="0"/>
 *         &lt;element name="tobaccoUse" type="{http://xmlns.calcfocus.com/services/calc}TobaccoUse" minOccurs="0"/>
 *         &lt;element name="primaryDividendOption" type="{http://xmlns.calcfocus.com/services/calc}DividendOption" minOccurs="0"/>
 *         &lt;element name="secondaryDividendOption" type="{http://xmlns.calcfocus.com/services/calc}DividendOption" minOccurs="0"/>
 *         &lt;element name="tertiaryDividendOption" type="{http://xmlns.calcfocus.com/services/calc}DividendOption" minOccurs="0"/>
 *         &lt;element name="nonforfeitureOption" type="{http://xmlns.calcfocus.com/services/calc}NonforfeitureOption" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsuranceChoicePreferences", propOrder = {
    "underwritingClass",
    "tobaccoUse",
    "primaryDividendOption",
    "secondaryDividendOption",
    "tertiaryDividendOption",
    "nonforfeitureOption"
})
public class InsuranceChoicePreferences {

    protected UnderwritingClass underwritingClass;
    protected TobaccoUse tobaccoUse;
    protected DividendOption primaryDividendOption;
    protected DividendOption secondaryDividendOption;
    protected DividendOption tertiaryDividendOption;
    protected NonforfeitureOption nonforfeitureOption;

    /**
     * Gets the value of the underwritingClass property.
     * 
     * @return
     *     possible object is
     *     {@link UnderwritingClass }
     *     
     */
    public UnderwritingClass getUnderwritingClass() {
        return underwritingClass;
    }

    /**
     * Sets the value of the underwritingClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnderwritingClass }
     *     
     */
    public void setUnderwritingClass(UnderwritingClass value) {
        this.underwritingClass = value;
    }

    /**
     * Gets the value of the tobaccoUse property.
     * 
     * @return
     *     possible object is
     *     {@link TobaccoUse }
     *     
     */
    public TobaccoUse getTobaccoUse() {
        return tobaccoUse;
    }

    /**
     * Sets the value of the tobaccoUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link TobaccoUse }
     *     
     */
    public void setTobaccoUse(TobaccoUse value) {
        this.tobaccoUse = value;
    }

    /**
     * Gets the value of the primaryDividendOption property.
     * 
     * @return
     *     possible object is
     *     {@link DividendOption }
     *     
     */
    public DividendOption getPrimaryDividendOption() {
        return primaryDividendOption;
    }

    /**
     * Sets the value of the primaryDividendOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link DividendOption }
     *     
     */
    public void setPrimaryDividendOption(DividendOption value) {
        this.primaryDividendOption = value;
    }

    /**
     * Gets the value of the secondaryDividendOption property.
     * 
     * @return
     *     possible object is
     *     {@link DividendOption }
     *     
     */
    public DividendOption getSecondaryDividendOption() {
        return secondaryDividendOption;
    }

    /**
     * Sets the value of the secondaryDividendOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link DividendOption }
     *     
     */
    public void setSecondaryDividendOption(DividendOption value) {
        this.secondaryDividendOption = value;
    }

    /**
     * Gets the value of the tertiaryDividendOption property.
     * 
     * @return
     *     possible object is
     *     {@link DividendOption }
     *     
     */
    public DividendOption getTertiaryDividendOption() {
        return tertiaryDividendOption;
    }

    /**
     * Sets the value of the tertiaryDividendOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link DividendOption }
     *     
     */
    public void setTertiaryDividendOption(DividendOption value) {
        this.tertiaryDividendOption = value;
    }

    /**
     * Gets the value of the nonforfeitureOption property.
     * 
     * @return
     *     possible object is
     *     {@link NonforfeitureOption }
     *     
     */
    public NonforfeitureOption getNonforfeitureOption() {
        return nonforfeitureOption;
    }

    /**
     * Sets the value of the nonforfeitureOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonforfeitureOption }
     *     
     */
    public void setNonforfeitureOption(NonforfeitureOption value) {
        this.nonforfeitureOption = value;
    }

}
