//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.23 at 11:48:17 AM EDT 
//


package com.selman.calcfocus.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LifeEventType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LifeEventType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Child"/>
 *     &lt;enumeration value="CitizenshipChange"/>
 *     &lt;enumeration value="DeathInFamily"/>
 *     &lt;enumeration value="Divorce"/>
 *     &lt;enumeration value="Marriage"/>
 *     &lt;enumeration value="HomePurchase"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LifeEventType")
@XmlEnum
public enum LifeEventType {

    @XmlEnumValue("Child")
    CHILD("Child"),
    @XmlEnumValue("CitizenshipChange")
    CITIZENSHIP_CHANGE("CitizenshipChange"),
    @XmlEnumValue("DeathInFamily")
    DEATH_IN_FAMILY("DeathInFamily"),
    @XmlEnumValue("Divorce")
    DIVORCE("Divorce"),
    @XmlEnumValue("Marriage")
    MARRIAGE("Marriage"),
    @XmlEnumValue("HomePurchase")
    HOME_PURCHASE("HomePurchase");
    private final String value;

    LifeEventType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LifeEventType fromValue(String v) {
        for (LifeEventType c: LifeEventType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
