//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.16 at 02:52:28 PM EST 
//


package com.selman.calcfocus.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.selman.calcfocus.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.selman.calcfocus.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CalculateRequest }
     * 
     */
    public CalculateRequest createCalculateRequest() {
        return new CalculateRequest();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Context }
     * 
     */
    public Context createContext() {
        return new Context();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicy() {
        return new Policy();
    }

    /**
     * Create an instance of {@link Party }
     * 
     */
    public Party createParty() {
        return new Party();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AnnualStatementAdminData }
     * 
     */
    public AnnualStatementAdminData createAnnualStatementAdminData() {
        return new AnnualStatementAdminData();
    }

    /**
     * Create an instance of {@link LifetimeFinancialAdviceProjection }
     * 
     */
    public LifetimeFinancialAdviceProjection createLifetimeFinancialAdviceProjection() {
        return new LifetimeFinancialAdviceProjection();
    }

    /**
     * Create an instance of {@link HistoricalFundData }
     * 
     */
    public HistoricalFundData createHistoricalFundData() {
        return new HistoricalFundData();
    }

    /**
     * Create an instance of {@link Coverage }
     * 
     */
    public Coverage createCoverage() {
        return new Coverage();
    }

    /**
     * Create an instance of {@link QABRiderTarget }
     * 
     */
    public QABRiderTarget createQABRiderTarget() {
        return new QABRiderTarget();
    }

    /**
     * Create an instance of {@link AnnualStatementFaceChangeSummary }
     * 
     */
    public AnnualStatementFaceChangeSummary createAnnualStatementFaceChangeSummary() {
        return new AnnualStatementFaceChangeSummary();
    }

    /**
     * Create an instance of {@link ConversionCoverageUpdates }
     * 
     */
    public ConversionCoverageUpdates createConversionCoverageUpdates() {
        return new ConversionCoverageUpdates();
    }

    /**
     * Create an instance of {@link PremiumTaxChargeDefinitions }
     * 
     */
    public PremiumTaxChargeDefinitions createPremiumTaxChargeDefinitions() {
        return new PremiumTaxChargeDefinitions();
    }

    /**
     * Create an instance of {@link InsurancePolicySummary }
     * 
     */
    public InsurancePolicySummary createInsurancePolicySummary() {
        return new InsurancePolicySummary();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link Scenario }
     * 
     */
    public Scenario createScenario() {
        return new Scenario();
    }

    /**
     * Create an instance of {@link HistoricalTransaction }
     * 
     */
    public HistoricalTransaction createHistoricalTransaction() {
        return new HistoricalTransaction();
    }

    /**
     * Create an instance of {@link PolicyCharge }
     * 
     */
    public PolicyCharge createPolicyCharge() {
        return new PolicyCharge();
    }

    /**
     * Create an instance of {@link ReInsurer }
     * 
     */
    public ReInsurer createReInsurer() {
        return new ReInsurer();
    }

    /**
     * Create an instance of {@link PredefinedScenariosLoanRepaymentSchedule }
     * 
     */
    public PredefinedScenariosLoanRepaymentSchedule createPredefinedScenariosLoanRepaymentSchedule() {
        return new PredefinedScenariosLoanRepaymentSchedule();
    }

    /**
     * Create an instance of {@link AvailableRider }
     * 
     */
    public AvailableRider createAvailableRider() {
        return new AvailableRider();
    }

    /**
     * Create an instance of {@link QABRider }
     * 
     */
    public QABRider createQABRider() {
        return new QABRider();
    }

    /**
     * Create an instance of {@link TransactionRequest }
     * 
     */
    public TransactionRequest createTransactionRequest() {
        return new TransactionRequest();
    }

    /**
     * Create an instance of {@link RiderInstructions }
     * 
     */
    public RiderInstructions createRiderInstructions() {
        return new RiderInstructions();
    }

    /**
     * Create an instance of {@link ReInsuranceData }
     * 
     */
    public ReInsuranceData createReInsuranceData() {
        return new ReInsuranceData();
    }

    /**
     * Create an instance of {@link Rates }
     * 
     */
    public Rates createRates() {
        return new Rates();
    }

    /**
     * Create an instance of {@link LifetimeGoals }
     * 
     */
    public LifetimeGoals createLifetimeGoals() {
        return new LifetimeGoals();
    }

    /**
     * Create an instance of {@link NameValue }
     * 
     */
    public NameValue createNameValue() {
        return new NameValue();
    }

    /**
     * Create an instance of {@link AdminChargeDefinitions }
     * 
     */
    public AdminChargeDefinitions createAdminChargeDefinitions() {
        return new AdminChargeDefinitions();
    }

    /**
     * Create an instance of {@link AgentSplit }
     * 
     */
    public AgentSplit createAgentSplit() {
        return new AgentSplit();
    }

    /**
     * Create an instance of {@link InsuranceChoicePreferences }
     * 
     */
    public InsuranceChoicePreferences createInsuranceChoicePreferences() {
        return new InsuranceChoicePreferences();
    }

    /**
     * Create an instance of {@link AddressAssociation }
     * 
     */
    public AddressAssociation createAddressAssociation() {
        return new AddressAssociation();
    }

    /**
     * Create an instance of {@link PredefinedScenario }
     * 
     */
    public PredefinedScenario createPredefinedScenario() {
        return new PredefinedScenario();
    }

    /**
     * Create an instance of {@link Financials }
     * 
     */
    public Financials createFinancials() {
        return new Financials();
    }

    /**
     * Create an instance of {@link RequestedIllustrationChange }
     * 
     */
    public RequestedIllustrationChange createRequestedIllustrationChange() {
        return new RequestedIllustrationChange();
    }

    /**
     * Create an instance of {@link FundAllocation }
     * 
     */
    public FundAllocation createFundAllocation() {
        return new FundAllocation();
    }

    /**
     * Create an instance of {@link Bequest }
     * 
     */
    public Bequest createBequest() {
        return new Bequest();
    }

    /**
     * Create an instance of {@link Debt }
     * 
     */
    public Debt createDebt() {
        return new Debt();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link HistoricProductOffer }
     * 
     */
    public HistoricProductOffer createHistoricProductOffer() {
        return new HistoricProductOffer();
    }

    /**
     * Create an instance of {@link PremiumChargeDefinitions }
     * 
     */
    public PremiumChargeDefinitions createPremiumChargeDefinitions() {
        return new PremiumChargeDefinitions();
    }

    /**
     * Create an instance of {@link PointInTime }
     * 
     */
    public PointInTime createPointInTime() {
        return new PointInTime();
    }

    /**
     * Create an instance of {@link BandedRateDefinition }
     * 
     */
    public BandedRateDefinition createBandedRateDefinition() {
        return new BandedRateDefinition();
    }

    /**
     * Create an instance of {@link InterestRequest }
     * 
     */
    public InterestRequest createInterestRequest() {
        return new InterestRequest();
    }

    /**
     * Create an instance of {@link LifeEvent }
     * 
     */
    public LifeEvent createLifeEvent() {
        return new LifeEvent();
    }

    /**
     * Create an instance of {@link ProductTypesToInclude }
     * 
     */
    public ProductTypesToInclude createProductTypesToInclude() {
        return new ProductTypesToInclude();
    }

    /**
     * Create an instance of {@link InsuranceLevel }
     * 
     */
    public InsuranceLevel createInsuranceLevel() {
        return new InsuranceLevel();
    }

    /**
     * Create an instance of {@link MonthEndValues }
     * 
     */
    public MonthEndValues createMonthEndValues() {
        return new MonthEndValues();
    }

    /**
     * Create an instance of {@link Asset }
     * 
     */
    public Asset createAsset() {
        return new Asset();
    }

    /**
     * Create an instance of {@link Fund }
     * 
     */
    public Fund createFund() {
        return new Fund();
    }

    /**
     * Create an instance of {@link Salary }
     * 
     */
    public Salary createSalary() {
        return new Salary();
    }

    /**
     * Create an instance of {@link Solve }
     * 
     */
    public Solve createSolve() {
        return new Solve();
    }

    /**
     * Create an instance of {@link FlatExtra }
     * 
     */
    public FlatExtra createFlatExtra() {
        return new FlatExtra();
    }

    /**
     * Create an instance of {@link SimpleRateDefinition }
     * 
     */
    public SimpleRateDefinition createSimpleRateDefinition() {
        return new SimpleRateDefinition();
    }

    /**
     * Create an instance of {@link AnnualStatementMonthlySummary }
     * 
     */
    public AnnualStatementMonthlySummary createAnnualStatementMonthlySummary() {
        return new AnnualStatementMonthlySummary();
    }

    /**
     * Create an instance of {@link PlannedPremium }
     * 
     */
    public PlannedPremium createPlannedPremium() {
        return new PlannedPremium();
    }

    /**
     * Create an instance of {@link PolicyLevelProductDefinitionOverrides }
     * 
     */
    public PolicyLevelProductDefinitionOverrides createPolicyLevelProductDefinitionOverrides() {
        return new PolicyLevelProductDefinitionOverrides();
    }

    /**
     * Create an instance of {@link AnnualStatementMonthlyTransaction }
     * 
     */
    public AnnualStatementMonthlyTransaction createAnnualStatementMonthlyTransaction() {
        return new AnnualStatementMonthlyTransaction();
    }

    /**
     * Create an instance of {@link YearValue }
     * 
     */
    public YearValue createYearValue() {
        return new YearValue();
    }

    /**
     * Create an instance of {@link Employment }
     * 
     */
    public Employment createEmployment() {
        return new Employment();
    }

    /**
     * Create an instance of {@link Income }
     * 
     */
    public Income createIncome() {
        return new Income();
    }

    /**
     * Create an instance of {@link Rate }
     * 
     */
    public Rate createRate() {
        return new Rate();
    }

    /**
     * Create an instance of {@link ReInsuranceCoverage }
     * 
     */
    public ReInsuranceCoverage createReInsuranceCoverage() {
        return new ReInsuranceCoverage();
    }

    /**
     * Create an instance of {@link HealthDetails }
     * 
     */
    public HealthDetails createHealthDetails() {
        return new HealthDetails();
    }

    /**
     * Create an instance of {@link AnchoredScenario }
     * 
     */
    public AnchoredScenario createAnchoredScenario() {
        return new AnchoredScenario();
    }

    /**
     * Create an instance of {@link UnpaidMonthaversaryDateArray }
     * 
     */
    public UnpaidMonthaversaryDateArray createUnpaidMonthaversaryDateArray() {
        return new UnpaidMonthaversaryDateArray();
    }

    /**
     * Create an instance of {@link ConversionValues }
     * 
     */
    public ConversionValues createConversionValues() {
        return new ConversionValues();
    }

    /**
     * Create an instance of {@link CoverageUpdates }
     * 
     */
    public CoverageUpdates createCoverageUpdates() {
        return new CoverageUpdates();
    }

}
