//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.26 at 10:39:22 PM EDT 
//


package com.selman.calcfocus.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PointInTime complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PointInTime">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="paidToDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="billedToDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="costBasis" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="isMEC" type="{http://xmlns.calcfocus.com/services/calc}YesNo" minOccurs="0"/>
 *         &lt;element name="sevenPayStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="sumOfPremiumPaidTAMRA" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfPremiumPaidDEFRA" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfPremiumPaidTAMRADurationOne" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfPremiumPaidTAMRADurationTwo" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfPremiumPaidTAMRADurationThree" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfPremiumPaidTAMRADurationFour" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfPremiumPaidTAMRADurationFive" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfPremiumPaidTAMRADurationSix" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfPremiumPaidTAMRADurationSeven" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sevenPayPremium" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sevenPayInitialAdjustmentValue" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="guidelineSinglePremium" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="guidelineLevelPremium" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="guidelineLevelPremiumSum" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="lowestDeathBenefitDuringSevenPayPeriod" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="unnecessaryPremiumIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="benefitIncreaseIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="unnecessaryGLP" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="unnecessaryGLPSum" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="unnecessaryGSP" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfPremiumsPaidToDateCurrentYear" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfPremiumChargePaidToDateCurrentYear" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfExpenseChargeCurrentYear" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfCOICurrentYear" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfAVInterestCurrentYear" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="maxExpenseChargeCurrentYear" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfPremiumPolicyholderPaidForNoLapseGuaranteeTest" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfPremiumRequiredToKeepNoLapseGuaranteeInforce" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="noLapseGuaranteeExpiryDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="sumOfPremiumPaid" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfLoansCurrentYear" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfLoanRepaymentsCurrentYear" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="sumOfWithdrawalsCurrentYear" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="paidUpInsuranceFaceAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="additionalInsuranceFaceAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="oneYearTermFaceAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="premiumReductionSuspense" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pendingDividend" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="lastAnniversaryCapitalizedInterest" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="deathBenefitTimeOfConversion" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="unloanedCashValueTimeOfConversion" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="loanedCashValueTimeOfConversion" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="loanPrincipalTimeOfConversion" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="fund" type="{http://xmlns.calcfocus.com/services/calc}Fund" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="unpaidMonthaversaryDateArray" type="{http://xmlns.calcfocus.com/services/calc}UnpaidMonthaversaryDateArray" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PointInTime", propOrder = {
    "effectiveDate",
    "paidToDate",
    "billedToDate",
    "costBasis",
    "isMEC",
    "sevenPayStartDate",
    "sumOfPremiumPaidTAMRA",
    "sumOfPremiumPaidDEFRA",
    "sumOfPremiumPaidTAMRADurationOne",
    "sumOfPremiumPaidTAMRADurationTwo",
    "sumOfPremiumPaidTAMRADurationThree",
    "sumOfPremiumPaidTAMRADurationFour",
    "sumOfPremiumPaidTAMRADurationFive",
    "sumOfPremiumPaidTAMRADurationSix",
    "sumOfPremiumPaidTAMRADurationSeven",
    "sevenPayPremium",
    "sevenPayInitialAdjustmentValue",
    "guidelineSinglePremium",
    "guidelineLevelPremium",
    "guidelineLevelPremiumSum",
    "lowestDeathBenefitDuringSevenPayPeriod",
    "unnecessaryPremiumIndicator",
    "benefitIncreaseIndicator",
    "unnecessaryGLP",
    "unnecessaryGLPSum",
    "unnecessaryGSP",
    "sumOfPremiumsPaidToDateCurrentYear",
    "sumOfPremiumChargePaidToDateCurrentYear",
    "sumOfExpenseChargeCurrentYear",
    "sumOfCOICurrentYear",
    "sumOfAVInterestCurrentYear",
    "maxExpenseChargeCurrentYear",
    "sumOfPremiumPolicyholderPaidForNoLapseGuaranteeTest",
    "sumOfPremiumRequiredToKeepNoLapseGuaranteeInforce",
    "noLapseGuaranteeExpiryDate",
    "sumOfPremiumPaid",
    "sumOfLoansCurrentYear",
    "sumOfLoanRepaymentsCurrentYear",
    "sumOfWithdrawalsCurrentYear",
    "paidUpInsuranceFaceAmount",
    "additionalInsuranceFaceAmount",
    "oneYearTermFaceAmount",
    "premiumReductionSuspense",
    "pendingDividend",
    "lastAnniversaryCapitalizedInterest",
    "reportingPeriodSumOfPremiumsPaid",
    "reportingPeriodSumOfPremiumChargePaid",
    "reportingPeriodSumOfExpenseCharge",
    "reportingPeriodSumOfCOI",
    "reportingPeriodSumOfAVInterest",
    "reportingPeriodReservesReleasedDeath",
    "reportingPeriodReservesReleasedOther",
    "deathBenefitTimeOfConversion",
    "unloanedCashValueTimeOfConversion",
    "loanedCashValueTimeOfConversion",
    "loanPrincipalTimeOfConversion",
    "fund",
    "unpaidMonthaversaryDateArray"
})
public class PointInTime {

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar effectiveDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar paidToDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar billedToDate;
    protected Double costBasis;
    protected YesNo isMEC;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar sevenPayStartDate;
    protected Double sumOfPremiumPaidTAMRA;
    protected Double sumOfPremiumPaidDEFRA;
    protected Double sumOfPremiumPaidTAMRADurationOne;
    protected Double sumOfPremiumPaidTAMRADurationTwo;
    protected Double sumOfPremiumPaidTAMRADurationThree;
    protected Double sumOfPremiumPaidTAMRADurationFour;
    protected Double sumOfPremiumPaidTAMRADurationFive;
    protected Double sumOfPremiumPaidTAMRADurationSix;
    protected Double sumOfPremiumPaidTAMRADurationSeven;
    protected Double sevenPayPremium;
    protected Double sevenPayInitialAdjustmentValue;
    protected Double guidelineSinglePremium;
    protected Double guidelineLevelPremium;
    protected Double guidelineLevelPremiumSum;
    protected Double lowestDeathBenefitDuringSevenPayPeriod;
    protected Boolean unnecessaryPremiumIndicator;
    protected Boolean benefitIncreaseIndicator;
    protected Double unnecessaryGLP;
    protected Double unnecessaryGLPSum;
    protected Double unnecessaryGSP;
    protected Double sumOfPremiumsPaidToDateCurrentYear;
    protected Double sumOfPremiumChargePaidToDateCurrentYear;
    protected Double sumOfExpenseChargeCurrentYear;
    protected Double sumOfCOICurrentYear;
    protected Double sumOfAVInterestCurrentYear;
    protected Double maxExpenseChargeCurrentYear;
    protected Double sumOfPremiumPolicyholderPaidForNoLapseGuaranteeTest;
    protected Double sumOfPremiumRequiredToKeepNoLapseGuaranteeInforce;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar noLapseGuaranteeExpiryDate;
    protected Double sumOfPremiumPaid;
    protected Double sumOfLoansCurrentYear;
    protected Double sumOfLoanRepaymentsCurrentYear;
    protected Double sumOfWithdrawalsCurrentYear;
    protected Double paidUpInsuranceFaceAmount;
    protected Double additionalInsuranceFaceAmount;
    protected Double oneYearTermFaceAmount;
    protected Double premiumReductionSuspense;
    protected Double pendingDividend;
    protected Double lastAnniversaryCapitalizedInterest;
    protected Double reportingPeriodSumOfPremiumsPaid;
    protected Double reportingPeriodSumOfPremiumChargePaid;
    protected Double reportingPeriodSumOfExpenseCharge;
    protected Double reportingPeriodSumOfCOI;
    protected Double reportingPeriodSumOfAVInterest;
    protected Double reportingPeriodReservesReleasedDeath;
    protected Double reportingPeriodReservesReleasedOther;
    protected Double deathBenefitTimeOfConversion;
    protected Double unloanedCashValueTimeOfConversion;
    protected Double loanedCashValueTimeOfConversion;
    protected Double loanPrincipalTimeOfConversion;
    protected List<Fund> fund;
    protected UnpaidMonthaversaryDateArray unpaidMonthaversaryDateArray;

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the paidToDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaidToDate() {
        return paidToDate;
    }

    /**
     * Sets the value of the paidToDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaidToDate(XMLGregorianCalendar value) {
        this.paidToDate = value;
    }

    /**
     * Gets the value of the billedToDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBilledToDate() {
        return billedToDate;
    }

    /**
     * Sets the value of the billedToDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBilledToDate(XMLGregorianCalendar value) {
        this.billedToDate = value;
    }

    /**
     * Gets the value of the costBasis property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCostBasis() {
        return costBasis;
    }

    /**
     * Sets the value of the costBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCostBasis(Double value) {
        this.costBasis = value;
    }

    /**
     * Gets the value of the isMEC property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getIsMEC() {
        return isMEC;
    }

    /**
     * Sets the value of the isMEC property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setIsMEC(YesNo value) {
        this.isMEC = value;
    }

    /**
     * Gets the value of the sevenPayStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSevenPayStartDate() {
        return sevenPayStartDate;
    }

    /**
     * Sets the value of the sevenPayStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSevenPayStartDate(XMLGregorianCalendar value) {
        this.sevenPayStartDate = value;
    }

    /**
     * Gets the value of the sumOfPremiumPaidTAMRA property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfPremiumPaidTAMRA() {
        return sumOfPremiumPaidTAMRA;
    }

    /**
     * Sets the value of the sumOfPremiumPaidTAMRA property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfPremiumPaidTAMRA(Double value) {
        this.sumOfPremiumPaidTAMRA = value;
    }

    /**
     * Gets the value of the sumOfPremiumPaidDEFRA property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfPremiumPaidDEFRA() {
        return sumOfPremiumPaidDEFRA;
    }

    /**
     * Sets the value of the sumOfPremiumPaidDEFRA property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfPremiumPaidDEFRA(Double value) {
        this.sumOfPremiumPaidDEFRA = value;
    }

    /**
     * Gets the value of the sumOfPremiumPaidTAMRADurationOne property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfPremiumPaidTAMRADurationOne() {
        return sumOfPremiumPaidTAMRADurationOne;
    }

    /**
     * Sets the value of the sumOfPremiumPaidTAMRADurationOne property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfPremiumPaidTAMRADurationOne(Double value) {
        this.sumOfPremiumPaidTAMRADurationOne = value;
    }

    /**
     * Gets the value of the sumOfPremiumPaidTAMRADurationTwo property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfPremiumPaidTAMRADurationTwo() {
        return sumOfPremiumPaidTAMRADurationTwo;
    }

    /**
     * Sets the value of the sumOfPremiumPaidTAMRADurationTwo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfPremiumPaidTAMRADurationTwo(Double value) {
        this.sumOfPremiumPaidTAMRADurationTwo = value;
    }

    /**
     * Gets the value of the sumOfPremiumPaidTAMRADurationThree property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfPremiumPaidTAMRADurationThree() {
        return sumOfPremiumPaidTAMRADurationThree;
    }

    /**
     * Sets the value of the sumOfPremiumPaidTAMRADurationThree property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfPremiumPaidTAMRADurationThree(Double value) {
        this.sumOfPremiumPaidTAMRADurationThree = value;
    }

    /**
     * Gets the value of the sumOfPremiumPaidTAMRADurationFour property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfPremiumPaidTAMRADurationFour() {
        return sumOfPremiumPaidTAMRADurationFour;
    }

    /**
     * Sets the value of the sumOfPremiumPaidTAMRADurationFour property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfPremiumPaidTAMRADurationFour(Double value) {
        this.sumOfPremiumPaidTAMRADurationFour = value;
    }

    /**
     * Gets the value of the sumOfPremiumPaidTAMRADurationFive property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfPremiumPaidTAMRADurationFive() {
        return sumOfPremiumPaidTAMRADurationFive;
    }

    /**
     * Sets the value of the sumOfPremiumPaidTAMRADurationFive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfPremiumPaidTAMRADurationFive(Double value) {
        this.sumOfPremiumPaidTAMRADurationFive = value;
    }

    /**
     * Gets the value of the sumOfPremiumPaidTAMRADurationSix property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfPremiumPaidTAMRADurationSix() {
        return sumOfPremiumPaidTAMRADurationSix;
    }

    /**
     * Sets the value of the sumOfPremiumPaidTAMRADurationSix property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfPremiumPaidTAMRADurationSix(Double value) {
        this.sumOfPremiumPaidTAMRADurationSix = value;
    }

    /**
     * Gets the value of the sumOfPremiumPaidTAMRADurationSeven property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfPremiumPaidTAMRADurationSeven() {
        return sumOfPremiumPaidTAMRADurationSeven;
    }

    /**
     * Sets the value of the sumOfPremiumPaidTAMRADurationSeven property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfPremiumPaidTAMRADurationSeven(Double value) {
        this.sumOfPremiumPaidTAMRADurationSeven = value;
    }

    /**
     * Gets the value of the sevenPayPremium property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSevenPayPremium() {
        return sevenPayPremium;
    }

    /**
     * Sets the value of the sevenPayPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSevenPayPremium(Double value) {
        this.sevenPayPremium = value;
    }

    /**
     * Gets the value of the sevenPayInitialAdjustmentValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSevenPayInitialAdjustmentValue() {
        return sevenPayInitialAdjustmentValue;
    }

    /**
     * Sets the value of the sevenPayInitialAdjustmentValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSevenPayInitialAdjustmentValue(Double value) {
        this.sevenPayInitialAdjustmentValue = value;
    }

    /**
     * Gets the value of the guidelineSinglePremium property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getGuidelineSinglePremium() {
        return guidelineSinglePremium;
    }

    /**
     * Sets the value of the guidelineSinglePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setGuidelineSinglePremium(Double value) {
        this.guidelineSinglePremium = value;
    }

    /**
     * Gets the value of the guidelineLevelPremium property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getGuidelineLevelPremium() {
        return guidelineLevelPremium;
    }

    /**
     * Sets the value of the guidelineLevelPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setGuidelineLevelPremium(Double value) {
        this.guidelineLevelPremium = value;
    }

    /**
     * Gets the value of the guidelineLevelPremiumSum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getGuidelineLevelPremiumSum() {
        return guidelineLevelPremiumSum;
    }

    /**
     * Sets the value of the guidelineLevelPremiumSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setGuidelineLevelPremiumSum(Double value) {
        this.guidelineLevelPremiumSum = value;
    }

    /**
     * Gets the value of the lowestDeathBenefitDuringSevenPayPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLowestDeathBenefitDuringSevenPayPeriod() {
        return lowestDeathBenefitDuringSevenPayPeriod;
    }

    /**
     * Sets the value of the lowestDeathBenefitDuringSevenPayPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLowestDeathBenefitDuringSevenPayPeriod(Double value) {
        this.lowestDeathBenefitDuringSevenPayPeriod = value;
    }

    /**
     * Gets the value of the unnecessaryPremiumIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUnnecessaryPremiumIndicator() {
        return unnecessaryPremiumIndicator;
    }

    /**
     * Sets the value of the unnecessaryPremiumIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUnnecessaryPremiumIndicator(Boolean value) {
        this.unnecessaryPremiumIndicator = value;
    }

    /**
     * Gets the value of the benefitIncreaseIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBenefitIncreaseIndicator() {
        return benefitIncreaseIndicator;
    }

    /**
     * Sets the value of the benefitIncreaseIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBenefitIncreaseIndicator(Boolean value) {
        this.benefitIncreaseIndicator = value;
    }

    /**
     * Gets the value of the unnecessaryGLP property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getUnnecessaryGLP() {
        return unnecessaryGLP;
    }

    /**
     * Sets the value of the unnecessaryGLP property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setUnnecessaryGLP(Double value) {
        this.unnecessaryGLP = value;
    }

    /**
     * Gets the value of the unnecessaryGLPSum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getUnnecessaryGLPSum() {
        return unnecessaryGLPSum;
    }

    /**
     * Sets the value of the unnecessaryGLPSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setUnnecessaryGLPSum(Double value) {
        this.unnecessaryGLPSum = value;
    }

    /**
     * Gets the value of the unnecessaryGSP property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getUnnecessaryGSP() {
        return unnecessaryGSP;
    }

    /**
     * Sets the value of the unnecessaryGSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setUnnecessaryGSP(Double value) {
        this.unnecessaryGSP = value;
    }

    /**
     * Gets the value of the sumOfPremiumsPaidToDateCurrentYear property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfPremiumsPaidToDateCurrentYear() {
        return sumOfPremiumsPaidToDateCurrentYear;
    }

    /**
     * Sets the value of the sumOfPremiumsPaidToDateCurrentYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfPremiumsPaidToDateCurrentYear(Double value) {
        this.sumOfPremiumsPaidToDateCurrentYear = value;
    }

    /**
     * Gets the value of the sumOfPremiumChargePaidToDateCurrentYear property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfPremiumChargePaidToDateCurrentYear() {
        return sumOfPremiumChargePaidToDateCurrentYear;
    }

    /**
     * Sets the value of the sumOfPremiumChargePaidToDateCurrentYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfPremiumChargePaidToDateCurrentYear(Double value) {
        this.sumOfPremiumChargePaidToDateCurrentYear = value;
    }

    /**
     * Gets the value of the sumOfExpenseChargeCurrentYear property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfExpenseChargeCurrentYear() {
        return sumOfExpenseChargeCurrentYear;
    }

    /**
     * Sets the value of the sumOfExpenseChargeCurrentYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfExpenseChargeCurrentYear(Double value) {
        this.sumOfExpenseChargeCurrentYear = value;
    }

    /**
     * Gets the value of the sumOfCOICurrentYear property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfCOICurrentYear() {
        return sumOfCOICurrentYear;
    }

    /**
     * Sets the value of the sumOfCOICurrentYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfCOICurrentYear(Double value) {
        this.sumOfCOICurrentYear = value;
    }

    /**
     * Gets the value of the sumOfAVInterestCurrentYear property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfAVInterestCurrentYear() {
        return sumOfAVInterestCurrentYear;
    }

    /**
     * Sets the value of the sumOfAVInterestCurrentYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfAVInterestCurrentYear(Double value) {
        this.sumOfAVInterestCurrentYear = value;
    }

    /**
     * Gets the value of the maxExpenseChargeCurrentYear property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxExpenseChargeCurrentYear() {
        return maxExpenseChargeCurrentYear;
    }

    /**
     * Sets the value of the maxExpenseChargeCurrentYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxExpenseChargeCurrentYear(Double value) {
        this.maxExpenseChargeCurrentYear = value;
    }

    /**
     * Gets the value of the sumOfPremiumPolicyholderPaidForNoLapseGuaranteeTest property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfPremiumPolicyholderPaidForNoLapseGuaranteeTest() {
        return sumOfPremiumPolicyholderPaidForNoLapseGuaranteeTest;
    }

    /**
     * Sets the value of the sumOfPremiumPolicyholderPaidForNoLapseGuaranteeTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfPremiumPolicyholderPaidForNoLapseGuaranteeTest(Double value) {
        this.sumOfPremiumPolicyholderPaidForNoLapseGuaranteeTest = value;
    }

    /**
     * Gets the value of the sumOfPremiumRequiredToKeepNoLapseGuaranteeInforce property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfPremiumRequiredToKeepNoLapseGuaranteeInforce() {
        return sumOfPremiumRequiredToKeepNoLapseGuaranteeInforce;
    }

    /**
     * Sets the value of the sumOfPremiumRequiredToKeepNoLapseGuaranteeInforce property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfPremiumRequiredToKeepNoLapseGuaranteeInforce(Double value) {
        this.sumOfPremiumRequiredToKeepNoLapseGuaranteeInforce = value;
    }

    /**
     * Gets the value of the noLapseGuaranteeExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNoLapseGuaranteeExpiryDate() {
        return noLapseGuaranteeExpiryDate;
    }

    /**
     * Sets the value of the noLapseGuaranteeExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNoLapseGuaranteeExpiryDate(XMLGregorianCalendar value) {
        this.noLapseGuaranteeExpiryDate = value;
    }

    /**
     * Gets the value of the sumOfPremiumPaid property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfPremiumPaid() {
        return sumOfPremiumPaid;
    }

    /**
     * Sets the value of the sumOfPremiumPaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfPremiumPaid(Double value) {
        this.sumOfPremiumPaid = value;
    }

    /**
     * Gets the value of the sumOfLoansCurrentYear property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfLoansCurrentYear() {
        return sumOfLoansCurrentYear;
    }

    /**
     * Sets the value of the sumOfLoansCurrentYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfLoansCurrentYear(Double value) {
        this.sumOfLoansCurrentYear = value;
    }

    /**
     * Gets the value of the sumOfLoanRepaymentsCurrentYear property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfLoanRepaymentsCurrentYear() {
        return sumOfLoanRepaymentsCurrentYear;
    }

    /**
     * Sets the value of the sumOfLoanRepaymentsCurrentYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfLoanRepaymentsCurrentYear(Double value) {
        this.sumOfLoanRepaymentsCurrentYear = value;
    }

    /**
     * Gets the value of the sumOfWithdrawalsCurrentYear property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSumOfWithdrawalsCurrentYear() {
        return sumOfWithdrawalsCurrentYear;
    }

    /**
     * Sets the value of the sumOfWithdrawalsCurrentYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSumOfWithdrawalsCurrentYear(Double value) {
        this.sumOfWithdrawalsCurrentYear = value;
    }

    /**
     * Gets the value of the paidUpInsuranceFaceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPaidUpInsuranceFaceAmount() {
        return paidUpInsuranceFaceAmount;
    }

    /**
     * Sets the value of the paidUpInsuranceFaceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPaidUpInsuranceFaceAmount(Double value) {
        this.paidUpInsuranceFaceAmount = value;
    }

    /**
     * Gets the value of the additionalInsuranceFaceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAdditionalInsuranceFaceAmount() {
        return additionalInsuranceFaceAmount;
    }

    /**
     * Sets the value of the additionalInsuranceFaceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAdditionalInsuranceFaceAmount(Double value) {
        this.additionalInsuranceFaceAmount = value;
    }

    /**
     * Gets the value of the oneYearTermFaceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getOneYearTermFaceAmount() {
        return oneYearTermFaceAmount;
    }

    /**
     * Sets the value of the oneYearTermFaceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOneYearTermFaceAmount(Double value) {
        this.oneYearTermFaceAmount = value;
    }

    /**
     * Gets the value of the premiumReductionSuspense property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPremiumReductionSuspense() {
        return premiumReductionSuspense;
    }

    /**
     * Sets the value of the premiumReductionSuspense property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPremiumReductionSuspense(Double value) {
        this.premiumReductionSuspense = value;
    }

    /**
     * Gets the value of the pendingDividend property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPendingDividend() {
        return pendingDividend;
    }

    /**
     * Sets the value of the pendingDividend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPendingDividend(Double value) {
        this.pendingDividend = value;
    }

    /**
     * Gets the value of the lastAnniversaryCapitalizedInterest property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLastAnniversaryCapitalizedInterest() {
        return lastAnniversaryCapitalizedInterest;
    }

    /**
     * Sets the value of the lastAnniversaryCapitalizedInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLastAnniversaryCapitalizedInterest(Double value) {
        this.lastAnniversaryCapitalizedInterest = value;
    }

    public Double getReportingPeriodSumOfPremiumsPaid() {
        return reportingPeriodSumOfPremiumsPaid;
    }
    public void setReportingPeriodSumOfPremiumsPaid(Double value) {
        this.reportingPeriodSumOfPremiumsPaid = value;
    }
    public Double getReportingPeriodSumOfPremiumChargePaid() {
        return reportingPeriodSumOfPremiumChargePaid;
    }
    public void setReportingPeriodSumOfPremiumChargePaid(Double value) {
        this.reportingPeriodSumOfPremiumChargePaid = value;
    }
    public Double getReportingPeriodSumOfExpenseCharge() {
        return reportingPeriodSumOfExpenseCharge;
    }
    public void setReportingPeriodSumOfExpenseCharge(Double value) {
        this.reportingPeriodSumOfExpenseCharge = value;
    }
    public Double getReportingPeriodSumOfCOI() {
        return reportingPeriodSumOfCOI;
    }
    public void setReportingPeriodSumOfCOI(Double value) {
        this.reportingPeriodSumOfCOI = value;
    }
    public Double getReportingPeriodSumOfAVInterest() {
        return reportingPeriodSumOfAVInterest;
    }
    public void setReportingPeriodSumOfAVInterest(Double value) {
        this.reportingPeriodSumOfAVInterest = value;
    }
    public Double getReportingPeriodReservesReleasedDeath() {
        return reportingPeriodReservesReleasedDeath;
    }
    public void setReportingPeriodReservesReleasedDeath(Double value) {
        this.reportingPeriodReservesReleasedDeath = value;
    }
    public Double getReportingPeriodReservesReleasedOther() {
        return reportingPeriodReservesReleasedOther;
    }
    public void setReportingPeriodReservesReleasedOther(Double value) {
        this.reportingPeriodReservesReleasedOther = value;
    }
    
    /*
     * Gets the value of the deathBenefitTimeOfConversion property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDeathBenefitTimeOfConversion() {
        return deathBenefitTimeOfConversion;
    }

    /**
     * Sets the value of the deathBenefitTimeOfConversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDeathBenefitTimeOfConversion(Double value) {
        this.deathBenefitTimeOfConversion = value;
    }

    /**
     * Gets the value of the unloanedCashValueTimeOfConversion property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getUnloanedCashValueTimeOfConversion() {
        return unloanedCashValueTimeOfConversion;
    }

    /**
     * Sets the value of the unloanedCashValueTimeOfConversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setUnloanedCashValueTimeOfConversion(Double value) {
        this.unloanedCashValueTimeOfConversion = value;
    }

    /**
     * Gets the value of the loanedCashValueTimeOfConversion property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLoanedCashValueTimeOfConversion() {
        return loanedCashValueTimeOfConversion;
    }

    /**
     * Sets the value of the loanedCashValueTimeOfConversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLoanedCashValueTimeOfConversion(Double value) {
        this.loanedCashValueTimeOfConversion = value;
    }

    /**
     * Gets the value of the loanPrincipalTimeOfConversion property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLoanPrincipalTimeOfConversion() {
        return loanPrincipalTimeOfConversion;
    }

    /**
     * Sets the value of the loanPrincipalTimeOfConversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLoanPrincipalTimeOfConversion(Double value) {
        this.loanPrincipalTimeOfConversion = value;
    }

    /**
     * Gets the value of the fund property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fund property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFund().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Fund }
     * 
     * 
     */
    public List<Fund> getFund() {
        if (fund == null) {
            fund = new ArrayList<Fund>();
        }
        return this.fund;
    }

    /**
     * Gets the value of the unpaidMonthaversaryDateArray property.
     * 
     * @return
     *     possible object is
     *     {@link UnpaidMonthaversaryDateArray }
     *     
     */
    public UnpaidMonthaversaryDateArray getUnpaidMonthaversaryDateArray() {
        return unpaidMonthaversaryDateArray;
    }

    /**
     * Sets the value of the unpaidMonthaversaryDateArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnpaidMonthaversaryDateArray }
     *     
     */
    public void setUnpaidMonthaversaryDateArray(UnpaidMonthaversaryDateArray value) {
        this.unpaidMonthaversaryDateArray = value;
    }

}
