//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.16 at 02:52:28 PM EST 
//


package com.selman.calcfocus.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Policy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Policy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="policyGUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="policyAdminStatus" type="{http://xmlns.calcfocus.com/services/calc}PolicyAdminStatus" minOccurs="0"/>
 *         &lt;element name="policyPhase" type="{http://xmlns.calcfocus.com/services/calc}PolicyPhase" minOccurs="0"/>
 *         &lt;element name="status" type="{http://xmlns.calcfocus.com/services/calc}IllustrationStatus" minOccurs="0"/>
 *         &lt;element name="outputInstruction" type="{http://xmlns.calcfocus.com/services/calc}OutputInstruction" minOccurs="0"/>
 *         &lt;element name="policyNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="carrierAdminSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="carrierCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="companyBlock" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="policyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="companyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="issueState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="groupCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="groupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="groupPolicyNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="groupPolicyEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="groupBillingId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="classCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="genderBlend" type="{http://xmlns.calcfocus.com/services/calc}GenderBlend" minOccurs="0"/>
 *         &lt;element name="premiumRatingFactor" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="coiRatingFactor" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="rates" type="{http://xmlns.calcfocus.com/services/calc}Rates" minOccurs="0"/>
 *         &lt;element name="taxQualified" type="{http://xmlns.calcfocus.com/services/calc}YesNo" minOccurs="0"/>
 *         &lt;element name="paymentMode" type="{http://xmlns.calcfocus.com/services/calc}PaymentMode" minOccurs="0"/>
 *         &lt;element name="paymentMethod" type="{http://xmlns.calcfocus.com/services/calc}PaymentMethod" minOccurs="0"/>
 *         &lt;element name="priorPaymentMethod" type="{http://xmlns.calcfocus.com/services/calc}PaymentMethod" minOccurs="0"/>
 *         &lt;element name="adminPaymentMode" type="{http://xmlns.calcfocus.com/services/calc}PaymentMode" minOccurs="0"/>
 *         &lt;element name="adminModalPremium" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="scenarioAssumedRate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="modalPremium" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="initialPremiumPayment" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="issueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="applicationSignedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="applicationReceivedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="lapseStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="preLapseStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="lastReinstatementDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="definitionOfLifeInsurance" type="{http://xmlns.calcfocus.com/services/calc}DefinitionOfLifeInsurance" minOccurs="0"/>
 *         &lt;element name="allowMEC" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="mECStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="loanInterestAssumption" type="{http://xmlns.calcfocus.com/services/calc}LoanInterestAssumption" minOccurs="0"/>
 *         &lt;element name="premiumSuspense" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="lastMonthaversaryCharge" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="annuityPayoutMode" type="{http://xmlns.calcfocus.com/services/calc}PaymentMode" minOccurs="0"/>
 *         &lt;element name="annuityPayoutGuaranteePeriod" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="annuityFixedPercentage" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="acceptInputAges" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="illustrationType" type="{http://xmlns.calcfocus.com/services/calc}IllustrationType" minOccurs="0"/>
 *         &lt;element name="primaryDividendOption" type="{http://xmlns.calcfocus.com/services/calc}DividendOption" minOccurs="0"/>
 *         &lt;element name="secondaryDividendOption" type="{http://xmlns.calcfocus.com/services/calc}DividendOption" minOccurs="0"/>
 *         &lt;element name="tertiaryDividendOption" type="{http://xmlns.calcfocus.com/services/calc}DividendOption" minOccurs="0"/>
 *         &lt;element name="nonforfeitureOption" type="{http://xmlns.calcfocus.com/services/calc}NonforfeitureOption" minOccurs="0"/>
 *         &lt;element name="targetDeathBenefit" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="targetDeathBenefitPremium" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="reinstatementRule" type="{http://xmlns.calcfocus.com/services/calc}ReinstatementRule" minOccurs="0"/>
 *         &lt;element name="reinstatementLoanRule" type="{http://xmlns.calcfocus.com/services/calc}ReinstatementLoanRule" minOccurs="0"/>
 *         &lt;element name="billingIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="illustrationProjection" type="{http://xmlns.calcfocus.com/services/calc}IllustrationProjection" minOccurs="0"/>
 *         &lt;element name="multipleScenarioRequestName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="onlineCycleUpHasOccurred" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="supplementalReportToInclude" type="{http://xmlns.calcfocus.com/services/calc}SupplementalReportType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="coverage" type="{http://xmlns.calcfocus.com/services/calc}Coverage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="availableRider" type="{http://xmlns.calcfocus.com/services/calc}AvailableRider" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="fundAllocation" type="{http://xmlns.calcfocus.com/services/calc}FundAllocation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pointInTime" type="{http://xmlns.calcfocus.com/services/calc}PointInTime" minOccurs="0"/>
 *         &lt;element name="pointInTimeOfConversion" type="{http://xmlns.calcfocus.com/services/calc}PointInTime" minOccurs="0"/>
 *         &lt;element name="coverageUpdates" type="{http://xmlns.calcfocus.com/services/calc}CoverageUpdates" minOccurs="0"/>
 *         &lt;element name="qabRiderTarget" type="{http://xmlns.calcfocus.com/services/calc}QABRiderTarget" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="scenario" type="{http://xmlns.calcfocus.com/services/calc}Scenario" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="predefinedScenario" type="{http://xmlns.calcfocus.com/services/calc}PredefinedScenario" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="predefinedScenariosLoanRepaymentSchedule" type="{http://xmlns.calcfocus.com/services/calc}PredefinedScenariosLoanRepaymentSchedule" minOccurs="0"/>
 *         &lt;element name="requestedIllustrationChange" type="{http://xmlns.calcfocus.com/services/calc}RequestedIllustrationChange" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="historicalTransaction" type="{http://xmlns.calcfocus.com/services/calc}HistoricalTransaction" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reinsurer" type="{http://xmlns.calcfocus.com/services/calc}ReInsurer" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reInsuranceType" type="{http://xmlns.calcfocus.com/services/calc}ReinsuranceType" minOccurs="0"/>
 *         &lt;element name="scenarioAssumedVariableRateArray" type="{http://www.w3.org/2001/XMLSchema}double" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="scenarioAssumedVariableRateIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="scenarioAssumedFundExpense" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="alternateScenarioIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="mrcSkipFirstYearCharge" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="mrcCOILoad" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="reInsuranceCoverage" type="{http://xmlns.calcfocus.com/services/calc}ReInsuranceCoverage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="policyLevelProductDefinitionOverrides" type="{http://xmlns.calcfocus.com/services/calc}PolicyLevelProductDefinitionOverrides" minOccurs="0"/>
 *         &lt;element name="historicalFundData" type="{http://xmlns.calcfocus.com/services/calc}HistoricalFundData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="plannedPremium" type="{http://xmlns.calcfocus.com/services/calc}PlannedPremium" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="agentSplit" type="{http://xmlns.calcfocus.com/services/calc}AgentSplit" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="previousYearEndValues" type="{http://xmlns.calcfocus.com/services/calc}MonthEndValues" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Policy", propOrder = {
    "policyGUID",
    "policyAdminStatus",
    "policyPhase",
    "status",
    "outputInstruction",
    "policyNumber",
    "accountNumber",
    "carrierAdminSystem",
    "carrierCode",
    "companyBlock",
    "policyName",
    "companyCode",
    "issueState",
    "groupCode",
    "groupName",
    "groupPolicyNumber",
    "groupPolicyEffectiveDate",
    "groupBillingId",
    "classCode",
    "genderBlend",
    "premiumRatingFactor",
    "coiRatingFactor",
    "rates",
    "taxQualified",
    "paymentMode",
    "paymentMethod",
    "priorPaymentMethod",
    "adminPaymentMode",
    "adminModalPremium",
    "scenarioAssumedRate",
    "modalPremium",
    "initialPremiumPayment",
    "effectiveDate",
    "issueDate",
    "applicationSignedDate",
    "applicationReceivedDate",
    "lapseStartDate",
    "preLapseStartDate",
    "lastReinstatementDate",
    "definitionOfLifeInsurance",
    "allowMEC",
    "mecStartDate",
    "loanInterestAssumption",
    "premiumSuspense",
    "lastMonthaversaryCharge",
    "annuityPayoutMode",
    "annuityPayoutGuaranteePeriod",
    "annuityFixedPercentage",
    "acceptInputAges",
    "illustrationType",
    "primaryDividendOption",
    "secondaryDividendOption",
    "tertiaryDividendOption",
    "nonforfeitureOption",
    "targetDeathBenefit",
    "targetDeathBenefitPremium",
    "reinstatementRule",
    "reinstatementLoanRule",
    "billingIndicator",
    "illustrationProjection",
    "multipleScenarioRequestName",
    "onlineCycleUpHasOccurred",
    "supplementalReportToInclude",
    "coverage",
    "availableRider",
    "fundAllocation",
    "pointInTime",
    "pointInTimeOfConversion",
    "coverageUpdates",
    "qabRiderTarget",
    "scenario",
    "predefinedScenario",
    "predefinedScenariosLoanRepaymentSchedule",
    "requestedIllustrationChange",
    "historicalTransaction",
    "reinsurer",
    "reInsuranceType",
    "scenarioAssumedVariableRateArray",
    "scenarioAssumedVariableRateIndicator",
    "scenarioAssumedFundExpense",
    "alternateScenarioIndicator",
    "mrcSkipFirstYearCharge",
    "mrcCOILoad",
    "reInsuranceCoverage",
    "policyLevelProductDefinitionOverrides",
    "historicalFundData",
    "plannedPremium",
    "agentSplit",
    "previousYearEndValues"
})
public class Policy {

    protected String policyGUID;
    protected PolicyAdminStatus policyAdminStatus;
    protected PolicyPhase policyPhase;
    protected IllustrationStatus status;
    protected OutputInstruction outputInstruction;
    protected String policyNumber;
    protected String accountNumber;
    protected String carrierAdminSystem;
    protected String carrierCode;
    protected String companyBlock;
    protected String policyName;
    @XmlElement(required = true)
    protected String companyCode;
    @XmlElement(required = true)
    protected String issueState;
    protected String groupCode;
    protected String groupName;
    protected String groupPolicyNumber;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar groupPolicyEffectiveDate;
    protected String groupBillingId;
    protected String classCode;
    protected GenderBlend genderBlend;
    protected Double premiumRatingFactor;
    protected Double coiRatingFactor;
    protected Rates rates;
    protected YesNo taxQualified;
    protected PaymentMode paymentMode;
    protected PaymentMethod paymentMethod;
    protected PaymentMethod priorPaymentMethod;
    protected PaymentMode adminPaymentMode;
    protected Double adminModalPremium;
    protected Double scenarioAssumedRate;
    protected Double modalPremium;
    protected Double initialPremiumPayment;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar effectiveDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar issueDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar applicationSignedDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar applicationReceivedDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lapseStartDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar preLapseStartDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastReinstatementDate;
    protected DefinitionOfLifeInsurance definitionOfLifeInsurance;
    protected Boolean allowMEC;
    @XmlElement(name = "mECStartDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mecStartDate;
    protected LoanInterestAssumption loanInterestAssumption;
    protected Double premiumSuspense;
    protected Double lastMonthaversaryCharge;
    protected PaymentMode annuityPayoutMode;
    protected Integer annuityPayoutGuaranteePeriod;
    protected Double annuityFixedPercentage;
    protected Boolean acceptInputAges;
    protected IllustrationType illustrationType;
    protected DividendOption primaryDividendOption;
    protected DividendOption secondaryDividendOption;
    protected DividendOption tertiaryDividendOption;
    protected NonforfeitureOption nonforfeitureOption;
    protected Double targetDeathBenefit;
    protected Double targetDeathBenefitPremium;
    protected ReinstatementRule reinstatementRule;
    protected ReinstatementLoanRule reinstatementLoanRule;
    protected Boolean billingIndicator;
    protected IllustrationProjection illustrationProjection;
    protected String multipleScenarioRequestName;
    protected Boolean onlineCycleUpHasOccurred;
    protected List<SupplementalReportType> supplementalReportToInclude;
    protected List<Coverage> coverage;
    protected List<AvailableRider> availableRider;
    protected List<FundAllocation> fundAllocation;
    protected PointInTime pointInTime;
    protected PointInTime pointInTimeOfConversion;
    protected CoverageUpdates coverageUpdates;
    protected List<QABRiderTarget> qabRiderTarget;
    protected List<Scenario> scenario;
    protected List<PredefinedScenario> predefinedScenario;
    protected PredefinedScenariosLoanRepaymentSchedule predefinedScenariosLoanRepaymentSchedule;
    protected List<RequestedIllustrationChange> requestedIllustrationChange;
    protected List<HistoricalTransaction> historicalTransaction;
    protected List<ReInsurer> reinsurer;
    protected ReinsuranceType reInsuranceType;
    @XmlElement(type = Double.class)
    protected List<Double> scenarioAssumedVariableRateArray;
    protected Boolean scenarioAssumedVariableRateIndicator;
    protected Double scenarioAssumedFundExpense;
    protected Boolean alternateScenarioIndicator;
    protected Boolean mrcSkipFirstYearCharge;
    protected Double mrcCOILoad;
    protected List<ReInsuranceCoverage> reInsuranceCoverage;
    protected PolicyLevelProductDefinitionOverrides policyLevelProductDefinitionOverrides;
    protected List<HistoricalFundData> historicalFundData;
    protected List<PlannedPremium> plannedPremium;
    protected List<AgentSplit> agentSplit;
    protected List<MonthEndValues> previousYearEndValues;

    /**
     * Gets the value of the policyGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyGUID() {
        return policyGUID;
    }

    /**
     * Sets the value of the policyGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyGUID(String value) {
        this.policyGUID = value;
    }

    /**
     * Gets the value of the policyAdminStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyAdminStatus }
     *     
     */
    public PolicyAdminStatus getPolicyAdminStatus() {
        return policyAdminStatus;
    }

    /**
     * Sets the value of the policyAdminStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyAdminStatus }
     *     
     */
    public void setPolicyAdminStatus(PolicyAdminStatus value) {
        this.policyAdminStatus = value;
    }

    /**
     * Gets the value of the policyPhase property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyPhase }
     *     
     */
    public PolicyPhase getPolicyPhase() {
        return policyPhase;
    }

    /**
     * Sets the value of the policyPhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyPhase }
     *     
     */
    public void setPolicyPhase(PolicyPhase value) {
        this.policyPhase = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link IllustrationStatus }
     *     
     */
    public IllustrationStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link IllustrationStatus }
     *     
     */
    public void setStatus(IllustrationStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the outputInstruction property.
     * 
     * @return
     *     possible object is
     *     {@link OutputInstruction }
     *     
     */
    public OutputInstruction getOutputInstruction() {
        return outputInstruction;
    }

    /**
     * Sets the value of the outputInstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputInstruction }
     *     
     */
    public void setOutputInstruction(OutputInstruction value) {
        this.outputInstruction = value;
    }

    /**
     * Gets the value of the policyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyNumber() {
        return policyNumber;
    }

    /**
     * Sets the value of the policyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyNumber(String value) {
        this.policyNumber = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the carrierAdminSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierAdminSystem() {
        return carrierAdminSystem;
    }

    /**
     * Sets the value of the carrierAdminSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierAdminSystem(String value) {
        this.carrierAdminSystem = value;
    }

    /**
     * Gets the value of the carrierCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierCode() {
        return carrierCode;
    }

    /**
     * Sets the value of the carrierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierCode(String value) {
        this.carrierCode = value;
    }

    /**
     * Gets the value of the companyBlock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyBlock() {
        return companyBlock;
    }

    /**
     * Sets the value of the companyBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyBlock(String value) {
        this.companyBlock = value;
    }

    /**
     * Gets the value of the policyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyName() {
        return policyName;
    }

    /**
     * Sets the value of the policyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyName(String value) {
        this.policyName = value;
    }

    /**
     * Gets the value of the companyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * Sets the value of the companyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyCode(String value) {
        this.companyCode = value;
    }

    /**
     * Gets the value of the issueState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueState() {
        return issueState;
    }

    /**
     * Sets the value of the issueState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueState(String value) {
        this.issueState = value;
    }

    /**
     * Gets the value of the groupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * Sets the value of the groupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupCode(String value) {
        this.groupCode = value;
    }

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the groupPolicyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupPolicyNumber() {
        return groupPolicyNumber;
    }

    /**
     * Sets the value of the groupPolicyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupPolicyNumber(String value) {
        this.groupPolicyNumber = value;
    }

    /**
     * Gets the value of the groupPolicyEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGroupPolicyEffectiveDate() {
        return groupPolicyEffectiveDate;
    }

    /**
     * Sets the value of the groupPolicyEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGroupPolicyEffectiveDate(XMLGregorianCalendar value) {
        this.groupPolicyEffectiveDate = value;
    }

    /**
     * Gets the value of the groupBillingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupBillingId() {
        return groupBillingId;
    }

    /**
     * Sets the value of the groupBillingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupBillingId(String value) {
        this.groupBillingId = value;
    }

    /**
     * Gets the value of the classCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * Sets the value of the classCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassCode(String value) {
        this.classCode = value;
    }

    /**
     * Gets the value of the genderBlend property.
     * 
     * @return
     *     possible object is
     *     {@link GenderBlend }
     *     
     */
    public GenderBlend getGenderBlend() {
        return genderBlend;
    }

    /**
     * Sets the value of the genderBlend property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenderBlend }
     *     
     */
    public void setGenderBlend(GenderBlend value) {
        this.genderBlend = value;
    }

    /**
     * Gets the value of the premiumRatingFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPremiumRatingFactor() {
        return premiumRatingFactor;
    }

    /**
     * Sets the value of the premiumRatingFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPremiumRatingFactor(Double value) {
        this.premiumRatingFactor = value;
    }

    /**
     * Gets the value of the coiRatingFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCoiRatingFactor() {
        return coiRatingFactor;
    }

    /**
     * Sets the value of the coiRatingFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCoiRatingFactor(Double value) {
        this.coiRatingFactor = value;
    }

    /**
     * Gets the value of the rates property.
     * 
     * @return
     *     possible object is
     *     {@link Rates }
     *     
     */
    public Rates getRates() {
        return rates;
    }

    /**
     * Sets the value of the rates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rates }
     *     
     */
    public void setRates(Rates value) {
        this.rates = value;
    }

    /**
     * Gets the value of the taxQualified property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getTaxQualified() {
        return taxQualified;
    }

    /**
     * Sets the value of the taxQualified property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setTaxQualified(YesNo value) {
        this.taxQualified = value;
    }

    /**
     * Gets the value of the paymentMode property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMode }
     *     
     */
    public PaymentMode getPaymentMode() {
        return paymentMode;
    }

    /**
     * Sets the value of the paymentMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMode }
     *     
     */
    public void setPaymentMode(PaymentMode value) {
        this.paymentMode = value;
    }

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMethod }
     *     
     */
    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMethod }
     *     
     */
    public void setPaymentMethod(PaymentMethod value) {
        this.paymentMethod = value;
    }

    /**
     * Gets the value of the priorPaymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMethod }
     *     
     */
    public PaymentMethod getPriorPaymentMethod() {
        return priorPaymentMethod;
    }

    /**
     * Sets the value of the priorPaymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMethod }
     *     
     */
    public void setPriorPaymentMethod(PaymentMethod value) {
        this.priorPaymentMethod = value;
    }

    /**
     * Gets the value of the adminPaymentMode property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMode }
     *     
     */
    public PaymentMode getAdminPaymentMode() {
        return adminPaymentMode;
    }

    /**
     * Sets the value of the adminPaymentMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMode }
     *     
     */
    public void setAdminPaymentMode(PaymentMode value) {
        this.adminPaymentMode = value;
    }

    /**
     * Gets the value of the adminModalPremium property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAdminModalPremium() {
        return adminModalPremium;
    }

    /**
     * Sets the value of the adminModalPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAdminModalPremium(Double value) {
        this.adminModalPremium = value;
    }

    /**
     * Gets the value of the scenarioAssumedRate property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getScenarioAssumedRate() {
        return scenarioAssumedRate;
    }

    /**
     * Sets the value of the scenarioAssumedRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setScenarioAssumedRate(Double value) {
        this.scenarioAssumedRate = value;
    }

    /**
     * Gets the value of the modalPremium property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getModalPremium() {
        return modalPremium;
    }

    /**
     * Sets the value of the modalPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setModalPremium(Double value) {
        this.modalPremium = value;
    }

    /**
     * Gets the value of the initialPremiumPayment property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getInitialPremiumPayment() {
        return initialPremiumPayment;
    }

    /**
     * Sets the value of the initialPremiumPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setInitialPremiumPayment(Double value) {
        this.initialPremiumPayment = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssueDate(XMLGregorianCalendar value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the applicationSignedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApplicationSignedDate() {
        return applicationSignedDate;
    }

    /**
     * Sets the value of the applicationSignedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApplicationSignedDate(XMLGregorianCalendar value) {
        this.applicationSignedDate = value;
    }

    /**
     * Gets the value of the applicationReceivedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApplicationReceivedDate() {
        return applicationReceivedDate;
    }

    /**
     * Sets the value of the applicationReceivedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApplicationReceivedDate(XMLGregorianCalendar value) {
        this.applicationReceivedDate = value;
    }

    /**
     * Gets the value of the lapseStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLapseStartDate() {
        return lapseStartDate;
    }

    /**
     * Sets the value of the lapseStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLapseStartDate(XMLGregorianCalendar value) {
        this.lapseStartDate = value;
    }

    /**
     * Gets the value of the preLapseStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPreLapseStartDate() {
        return preLapseStartDate;
    }

    /**
     * Sets the value of the preLapseStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPreLapseStartDate(XMLGregorianCalendar value) {
        this.preLapseStartDate = value;
    }

    /**
     * Gets the value of the lastReinstatementDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastReinstatementDate() {
        return lastReinstatementDate;
    }

    /**
     * Sets the value of the lastReinstatementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastReinstatementDate(XMLGregorianCalendar value) {
        this.lastReinstatementDate = value;
    }

    /**
     * Gets the value of the definitionOfLifeInsurance property.
     * 
     * @return
     *     possible object is
     *     {@link DefinitionOfLifeInsurance }
     *     
     */
    public DefinitionOfLifeInsurance getDefinitionOfLifeInsurance() {
        return definitionOfLifeInsurance;
    }

    /**
     * Sets the value of the definitionOfLifeInsurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefinitionOfLifeInsurance }
     *     
     */
    public void setDefinitionOfLifeInsurance(DefinitionOfLifeInsurance value) {
        this.definitionOfLifeInsurance = value;
    }

    /**
     * Gets the value of the allowMEC property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowMEC() {
        return allowMEC;
    }

    /**
     * Sets the value of the allowMEC property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowMEC(Boolean value) {
        this.allowMEC = value;
    }

    /**
     * Gets the value of the mecStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMECStartDate() {
        return mecStartDate;
    }

    /**
     * Sets the value of the mecStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMECStartDate(XMLGregorianCalendar value) {
        this.mecStartDate = value;
    }

    /**
     * Gets the value of the loanInterestAssumption property.
     * 
     * @return
     *     possible object is
     *     {@link LoanInterestAssumption }
     *     
     */
    public LoanInterestAssumption getLoanInterestAssumption() {
        return loanInterestAssumption;
    }

    /**
     * Sets the value of the loanInterestAssumption property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanInterestAssumption }
     *     
     */
    public void setLoanInterestAssumption(LoanInterestAssumption value) {
        this.loanInterestAssumption = value;
    }

    /**
     * Gets the value of the premiumSuspense property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPremiumSuspense() {
        return premiumSuspense;
    }

    /**
     * Sets the value of the premiumSuspense property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPremiumSuspense(Double value) {
        this.premiumSuspense = value;
    }

    /**
     * Gets the value of the lastMonthaversaryCharge property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLastMonthaversaryCharge() {
        return lastMonthaversaryCharge;
    }

    /**
     * Sets the value of the lastMonthaversaryCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLastMonthaversaryCharge(Double value) {
        this.lastMonthaversaryCharge = value;
    }

    /**
     * Gets the value of the annuityPayoutMode property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMode }
     *     
     */
    public PaymentMode getAnnuityPayoutMode() {
        return annuityPayoutMode;
    }

    /**
     * Sets the value of the annuityPayoutMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMode }
     *     
     */
    public void setAnnuityPayoutMode(PaymentMode value) {
        this.annuityPayoutMode = value;
    }

    /**
     * Gets the value of the annuityPayoutGuaranteePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAnnuityPayoutGuaranteePeriod() {
        return annuityPayoutGuaranteePeriod;
    }

    /**
     * Sets the value of the annuityPayoutGuaranteePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAnnuityPayoutGuaranteePeriod(Integer value) {
        this.annuityPayoutGuaranteePeriod = value;
    }

    /**
     * Gets the value of the annuityFixedPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAnnuityFixedPercentage() {
        return annuityFixedPercentage;
    }

    /**
     * Sets the value of the annuityFixedPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAnnuityFixedPercentage(Double value) {
        this.annuityFixedPercentage = value;
    }

    /**
     * Gets the value of the acceptInputAges property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAcceptInputAges() {
        return acceptInputAges;
    }

    /**
     * Sets the value of the acceptInputAges property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAcceptInputAges(Boolean value) {
        this.acceptInputAges = value;
    }

    /**
     * Gets the value of the illustrationType property.
     * 
     * @return
     *     possible object is
     *     {@link IllustrationType }
     *     
     */
    public IllustrationType getIllustrationType() {
        return illustrationType;
    }

    /**
     * Sets the value of the illustrationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IllustrationType }
     *     
     */
    public void setIllustrationType(IllustrationType value) {
        this.illustrationType = value;
    }

    /**
     * Gets the value of the primaryDividendOption property.
     * 
     * @return
     *     possible object is
     *     {@link DividendOption }
     *     
     */
    public DividendOption getPrimaryDividendOption() {
        return primaryDividendOption;
    }

    /**
     * Sets the value of the primaryDividendOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link DividendOption }
     *     
     */
    public void setPrimaryDividendOption(DividendOption value) {
        this.primaryDividendOption = value;
    }

    /**
     * Gets the value of the secondaryDividendOption property.
     * 
     * @return
     *     possible object is
     *     {@link DividendOption }
     *     
     */
    public DividendOption getSecondaryDividendOption() {
        return secondaryDividendOption;
    }

    /**
     * Sets the value of the secondaryDividendOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link DividendOption }
     *     
     */
    public void setSecondaryDividendOption(DividendOption value) {
        this.secondaryDividendOption = value;
    }

    /**
     * Gets the value of the tertiaryDividendOption property.
     * 
     * @return
     *     possible object is
     *     {@link DividendOption }
     *     
     */
    public DividendOption getTertiaryDividendOption() {
        return tertiaryDividendOption;
    }

    /**
     * Sets the value of the tertiaryDividendOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link DividendOption }
     *     
     */
    public void setTertiaryDividendOption(DividendOption value) {
        this.tertiaryDividendOption = value;
    }

    /**
     * Gets the value of the nonforfeitureOption property.
     * 
     * @return
     *     possible object is
     *     {@link NonforfeitureOption }
     *     
     */
    public NonforfeitureOption getNonforfeitureOption() {
        return nonforfeitureOption;
    }

    /**
     * Sets the value of the nonforfeitureOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonforfeitureOption }
     *     
     */
    public void setNonforfeitureOption(NonforfeitureOption value) {
        this.nonforfeitureOption = value;
    }

    /**
     * Gets the value of the targetDeathBenefit property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTargetDeathBenefit() {
        return targetDeathBenefit;
    }

    /**
     * Sets the value of the targetDeathBenefit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTargetDeathBenefit(Double value) {
        this.targetDeathBenefit = value;
    }

    /**
     * Gets the value of the targetDeathBenefitPremium property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTargetDeathBenefitPremium() {
        return targetDeathBenefitPremium;
    }

    /**
     * Sets the value of the targetDeathBenefitPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTargetDeathBenefitPremium(Double value) {
        this.targetDeathBenefitPremium = value;
    }

    /**
     * Gets the value of the reinstatementRule property.
     * 
     * @return
     *     possible object is
     *     {@link ReinstatementRule }
     *     
     */
    public ReinstatementRule getReinstatementRule() {
        return reinstatementRule;
    }

    /**
     * Sets the value of the reinstatementRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReinstatementRule }
     *     
     */
    public void setReinstatementRule(ReinstatementRule value) {
        this.reinstatementRule = value;
    }

    /**
     * Gets the value of the reinstatementLoanRule property.
     * 
     * @return
     *     possible object is
     *     {@link ReinstatementLoanRule }
     *     
     */
    public ReinstatementLoanRule getReinstatementLoanRule() {
        return reinstatementLoanRule;
    }

    /**
     * Sets the value of the reinstatementLoanRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReinstatementLoanRule }
     *     
     */
    public void setReinstatementLoanRule(ReinstatementLoanRule value) {
        this.reinstatementLoanRule = value;
    }

    /**
     * Gets the value of the billingIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBillingIndicator() {
        return billingIndicator;
    }

    /**
     * Sets the value of the billingIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBillingIndicator(Boolean value) {
        this.billingIndicator = value;
    }

    /**
     * Gets the value of the illustrationProjection property.
     * 
     * @return
     *     possible object is
     *     {@link IllustrationProjection }
     *     
     */
    public IllustrationProjection getIllustrationProjection() {
        return illustrationProjection;
    }

    /**
     * Sets the value of the illustrationProjection property.
     * 
     * @param value
     *     allowed object is
     *     {@link IllustrationProjection }
     *     
     */
    public void setIllustrationProjection(IllustrationProjection value) {
        this.illustrationProjection = value;
    }

    /**
     * Gets the value of the multipleScenarioRequestName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultipleScenarioRequestName() {
        return multipleScenarioRequestName;
    }

    /**
     * Sets the value of the multipleScenarioRequestName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultipleScenarioRequestName(String value) {
        this.multipleScenarioRequestName = value;
    }

    /**
     * Gets the value of the onlineCycleUpHasOccurred property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOnlineCycleUpHasOccurred() {
        return onlineCycleUpHasOccurred;
    }

    /**
     * Sets the value of the onlineCycleUpHasOccurred property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOnlineCycleUpHasOccurred(Boolean value) {
        this.onlineCycleUpHasOccurred = value;
    }

    /**
     * Gets the value of the supplementalReportToInclude property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supplementalReportToInclude property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupplementalReportToInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupplementalReportType }
     * 
     * 
     */
    public List<SupplementalReportType> getSupplementalReportToInclude() {
        if (supplementalReportToInclude == null) {
            supplementalReportToInclude = new ArrayList<SupplementalReportType>();
        }
        return this.supplementalReportToInclude;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coverage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoverage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coverage }
     * 
     * 
     */
    public List<Coverage> getCoverage() {
        if (coverage == null) {
            coverage = new ArrayList<Coverage>();
        }
        return this.coverage;
    }

    /**
     * Gets the value of the availableRider property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the availableRider property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvailableRider().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AvailableRider }
     * 
     * 
     */
    public List<AvailableRider> getAvailableRider() {
        if (availableRider == null) {
            availableRider = new ArrayList<AvailableRider>();
        }
        return this.availableRider;
    }

    /**
     * Gets the value of the fundAllocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fundAllocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFundAllocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FundAllocation }
     * 
     * 
     */
    public List<FundAllocation> getFundAllocation() {
        if (fundAllocation == null) {
            fundAllocation = new ArrayList<FundAllocation>();
        }
        return this.fundAllocation;
    }

    /**
     * Gets the value of the pointInTime property.
     * 
     * @return
     *     possible object is
     *     {@link PointInTime }
     *     
     */
    public PointInTime getPointInTime() {
        return pointInTime;
    }

    /**
     * Sets the value of the pointInTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointInTime }
     *     
     */
    public void setPointInTime(PointInTime value) {
        this.pointInTime = value;
    }

    /**
     * Gets the value of the pointInTimeOfConversion property.
     * 
     * @return
     *     possible object is
     *     {@link PointInTime }
     *     
     */
    public PointInTime getPointInTimeOfConversion() {
        return pointInTimeOfConversion;
    }

    /**
     * Sets the value of the pointInTimeOfConversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointInTime }
     *     
     */
    public void setPointInTimeOfConversion(PointInTime value) {
        this.pointInTimeOfConversion = value;
    }

    /**
     * Gets the value of the coverageUpdates property.
     * 
     * @return
     *     possible object is
     *     {@link CoverageUpdates }
     *     
     */
    public CoverageUpdates getCoverageUpdates() {
        return coverageUpdates;
    }

    /**
     * Sets the value of the coverageUpdates property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoverageUpdates }
     *     
     */
    public void setCoverageUpdates(CoverageUpdates value) {
        this.coverageUpdates = value;
    }

    /**
     * Gets the value of the qabRiderTarget property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qabRiderTarget property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQabRiderTarget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QABRiderTarget }
     * 
     * 
     */
    public List<QABRiderTarget> getQabRiderTarget() {
        if (qabRiderTarget == null) {
            qabRiderTarget = new ArrayList<QABRiderTarget>();
        }
        return this.qabRiderTarget;
    }

    /**
     * Gets the value of the scenario property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scenario property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScenario().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Scenario }
     * 
     * 
     */
    public List<Scenario> getScenario() {
        if (scenario == null) {
            scenario = new ArrayList<Scenario>();
        }
        return this.scenario;
    }

    /**
     * Gets the value of the predefinedScenario property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the predefinedScenario property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPredefinedScenario().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PredefinedScenario }
     * 
     * 
     */
    public List<PredefinedScenario> getPredefinedScenario() {
        if (predefinedScenario == null) {
            predefinedScenario = new ArrayList<PredefinedScenario>();
        }
        return this.predefinedScenario;
    }

    /**
     * Gets the value of the predefinedScenariosLoanRepaymentSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link PredefinedScenariosLoanRepaymentSchedule }
     *     
     */
    public PredefinedScenariosLoanRepaymentSchedule getPredefinedScenariosLoanRepaymentSchedule() {
        return predefinedScenariosLoanRepaymentSchedule;
    }

    /**
     * Sets the value of the predefinedScenariosLoanRepaymentSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link PredefinedScenariosLoanRepaymentSchedule }
     *     
     */
    public void setPredefinedScenariosLoanRepaymentSchedule(PredefinedScenariosLoanRepaymentSchedule value) {
        this.predefinedScenariosLoanRepaymentSchedule = value;
    }

    /**
     * Gets the value of the requestedIllustrationChange property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestedIllustrationChange property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestedIllustrationChange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequestedIllustrationChange }
     * 
     * 
     */
    public List<RequestedIllustrationChange> getRequestedIllustrationChange() {
        if (requestedIllustrationChange == null) {
            requestedIllustrationChange = new ArrayList<RequestedIllustrationChange>();
        }
        return this.requestedIllustrationChange;
    }

    /**
     * Gets the value of the historicalTransaction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the historicalTransaction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHistoricalTransaction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HistoricalTransaction }
     * 
     * 
     */
    public List<HistoricalTransaction> getHistoricalTransaction() {
        if (historicalTransaction == null) {
            historicalTransaction = new ArrayList<HistoricalTransaction>();
        }
        return this.historicalTransaction;
    }

    /**
     * Gets the value of the reinsurer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reinsurer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReinsurer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReInsurer }
     * 
     * 
     */
    public List<ReInsurer> getReinsurer() {
        if (reinsurer == null) {
            reinsurer = new ArrayList<ReInsurer>();
        }
        return this.reinsurer;
    }

    /**
     * Gets the value of the reInsuranceType property.
     * 
     * @return
     *     possible object is
     *     {@link ReinsuranceType }
     *     
     */
    public ReinsuranceType getReInsuranceType() {
        return reInsuranceType;
    }

    /**
     * Sets the value of the reInsuranceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReinsuranceType }
     *     
     */
    public void setReInsuranceType(ReinsuranceType value) {
        this.reInsuranceType = value;
    }

    /**
     * Gets the value of the scenarioAssumedVariableRateArray property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scenarioAssumedVariableRateArray property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScenarioAssumedVariableRateArray().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getScenarioAssumedVariableRateArray() {
        if (scenarioAssumedVariableRateArray == null) {
            scenarioAssumedVariableRateArray = new ArrayList<Double>();
        }
        return this.scenarioAssumedVariableRateArray;
    }

    /**
     * Gets the value of the scenarioAssumedVariableRateIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isScenarioAssumedVariableRateIndicator() {
        return scenarioAssumedVariableRateIndicator;
    }

    /**
     * Sets the value of the scenarioAssumedVariableRateIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setScenarioAssumedVariableRateIndicator(Boolean value) {
        this.scenarioAssumedVariableRateIndicator = value;
    }

    /**
     * Gets the value of the scenarioAssumedFundExpense property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getScenarioAssumedFundExpense() {
        return scenarioAssumedFundExpense;
    }

    /**
     * Sets the value of the scenarioAssumedFundExpense property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setScenarioAssumedFundExpense(Double value) {
        this.scenarioAssumedFundExpense = value;
    }

    /**
     * Gets the value of the alternateScenarioIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAlternateScenarioIndicator() {
        return alternateScenarioIndicator;
    }

    /**
     * Sets the value of the alternateScenarioIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAlternateScenarioIndicator(Boolean value) {
        this.alternateScenarioIndicator = value;
    }

    /**
     * Gets the value of the mrcSkipFirstYearCharge property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMrcSkipFirstYearCharge() {
        return mrcSkipFirstYearCharge;
    }

    /**
     * Sets the value of the mrcSkipFirstYearCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMrcSkipFirstYearCharge(Boolean value) {
        this.mrcSkipFirstYearCharge = value;
    }

    /**
     * Gets the value of the mrcCOILoad property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMrcCOILoad() {
        return mrcCOILoad;
    }

    /**
     * Sets the value of the mrcCOILoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMrcCOILoad(Double value) {
        this.mrcCOILoad = value;
    }

    /**
     * Gets the value of the reInsuranceCoverage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reInsuranceCoverage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReInsuranceCoverage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReInsuranceCoverage }
     * 
     * 
     */
    public List<ReInsuranceCoverage> getReInsuranceCoverage() {
        if (reInsuranceCoverage == null) {
            reInsuranceCoverage = new ArrayList<ReInsuranceCoverage>();
        }
        return this.reInsuranceCoverage;
    }

    /**
     * Gets the value of the policyLevelProductDefinitionOverrides property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyLevelProductDefinitionOverrides }
     *     
     */
    public PolicyLevelProductDefinitionOverrides getPolicyLevelProductDefinitionOverrides() {
        return policyLevelProductDefinitionOverrides;
    }

    /**
     * Sets the value of the policyLevelProductDefinitionOverrides property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyLevelProductDefinitionOverrides }
     *     
     */
    public void setPolicyLevelProductDefinitionOverrides(PolicyLevelProductDefinitionOverrides value) {
        this.policyLevelProductDefinitionOverrides = value;
    }

    /**
     * Gets the value of the historicalFundData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the historicalFundData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHistoricalFundData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HistoricalFundData }
     * 
     * 
     */
    public List<HistoricalFundData> getHistoricalFundData() {
        if (historicalFundData == null) {
            historicalFundData = new ArrayList<HistoricalFundData>();
        }
        return this.historicalFundData;
    }

    /**
     * Gets the value of the plannedPremium property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plannedPremium property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlannedPremium().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlannedPremium }
     * 
     * 
     */
    public List<PlannedPremium> getPlannedPremium() {
        if (plannedPremium == null) {
            plannedPremium = new ArrayList<PlannedPremium>();
        }
        return this.plannedPremium;
    }

    /**
     * Gets the value of the agentSplit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agentSplit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgentSplit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgentSplit }
     * 
     * 
     */
    public List<AgentSplit> getAgentSplit() {
        if (agentSplit == null) {
            agentSplit = new ArrayList<AgentSplit>();
        }
        return this.agentSplit;
    }

    /**
     * Gets the value of the previousYearEndValues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the previousYearEndValues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreviousYearEndValues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonthEndValues }
     * 
     * 
     */
    public List<MonthEndValues> getPreviousYearEndValues() {
        if (previousYearEndValues == null) {
            previousYearEndValues = new ArrayList<MonthEndValues>();
        }
        return this.previousYearEndValues;
    }

}
