//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.26 at 10:39:22 PM EDT 
//


package com.selman.calcfocus.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PremiumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PremiumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="GuidelineLevel"/>
 *     &lt;enumeration value="GuidelineSingle"/>
 *     &lt;enumeration value="Minimum"/>
 *     &lt;enumeration value="MinimumToIssue"/>
 *     &lt;enumeration value="PaidToDate"/>
 *     &lt;enumeration value="PaidUpAdditions"/>
 *     &lt;enumeration value="Planned"/>
 *     &lt;enumeration value="SecondaryGuarantee"/>
 *     &lt;enumeration value="SevenPay"/>
 *     &lt;enumeration value="Target"/>
 *     &lt;enumeration value="TargetPremiumAtIllustrationStart"/>
 *     &lt;enumeration value="Reinstatement"/>
 *     &lt;enumeration value="ReinstatementDeficit"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PremiumType")
@XmlEnum
public enum PremiumType {

    @XmlEnumValue("GuidelineLevel")
    GUIDELINE_LEVEL("GuidelineLevel"),
    @XmlEnumValue("GuidelineSingle")
    GUIDELINE_SINGLE("GuidelineSingle"),
    @XmlEnumValue("Minimum")
    MINIMUM("Minimum"),
    @XmlEnumValue("MinimumToIssue")
    MINIMUM_TO_ISSUE("MinimumToIssue"),
    @XmlEnumValue("PaidToDate")
    PAID_TO_DATE("PaidToDate"),
    @XmlEnumValue("PaidUpAdditions")
    PAID_UP_ADDITIONS("PaidUpAdditions"),
    @XmlEnumValue("Planned")
    PLANNED("Planned"),
    @XmlEnumValue("SecondaryGuarantee")
    SECONDARY_GUARANTEE("SecondaryGuarantee"),
    @XmlEnumValue("SevenPay")
    SEVEN_PAY("SevenPay"),
    @XmlEnumValue("Target")
    TARGET("Target"),
    @XmlEnumValue("TargetPremiumAtIllustrationStart")
    TARGET_PREMIUM_AT_ILLUSTRATION_START("TargetPremiumAtIllustrationStart"),
    @XmlEnumValue("Reinstatement")
    REINSTATEMENT("Reinstatement"),
    @XmlEnumValue("ReinstatementDeficit")
    REINSTATEMENT_DEFICIT("ReinstatementDeficit");
    private final String value;

    PremiumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PremiumType fromValue(String v) {
        for (PremiumType c: PremiumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
