//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.23 at 11:48:17 AM EDT 
//


package com.selman.calcfocus.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestedIllustrationChange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestedIllustrationChange">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userEnteredRequestedIllustrationChange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestedIllustrationChange", propOrder = {
    "userEnteredRequestedIllustrationChange"
})
public class RequestedIllustrationChange {

    @XmlElement(required = true)
    protected String userEnteredRequestedIllustrationChange;

    /**
     * Gets the value of the userEnteredRequestedIllustrationChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserEnteredRequestedIllustrationChange() {
        return userEnteredRequestedIllustrationChange;
    }

    /**
     * Sets the value of the userEnteredRequestedIllustrationChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserEnteredRequestedIllustrationChange(String value) {
        this.userEnteredRequestedIllustrationChange = value;
    }

}
