//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.23 at 11:48:17 AM EDT 
//


package com.selman.calcfocus.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScenarioType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ScenarioType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Current"/>
 *     &lt;enumeration value="CurrentInput"/>
 *     &lt;enumeration value="Guaranteed"/>
 *     &lt;enumeration value="GuaranteedInput"/>
 *     &lt;enumeration value="MidPoint"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ScenarioType")
@XmlEnum
public enum ScenarioType {

    @XmlEnumValue("Current")
    CURRENT("Current"),
    @XmlEnumValue("CurrentInput")
    CURRENT_INPUT("CurrentInput"),
    @XmlEnumValue("Guaranteed")
    GUARANTEED("Guaranteed"),
    @XmlEnumValue("GuaranteedInput")
    GUARANTEED_INPUT("GuaranteedInput"),
    @XmlEnumValue("MidPoint")
    MID_POINT("MidPoint");
    private final String value;

    ScenarioType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScenarioType fromValue(String v) {
        for (ScenarioType c: ScenarioType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
