//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.16 at 02:52:28 PM EST 
//


package com.selman.calcfocus.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionRequestAmountRule.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransactionRequestAmountRule">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CalculatedPremium"/>
 *     &lt;enumeration value="CurrentAmount"/>
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="PercentageOfInvestment"/>
 *     &lt;enumeration value="SpecifiedAmount"/>
 *     &lt;enumeration value="Solve"/>
 *     &lt;enumeration value="TargetPremium"/>
 *     &lt;enumeration value="SevenPayPremium"/>
 *     &lt;enumeration value="MaximumAllowed"/>
 *     &lt;enumeration value="GuidelineSinglePremium"/>
 *     &lt;enumeration value="GuidelineLevelPremium"/>
 *     &lt;enumeration value="MinimumPremium"/>
 *     &lt;enumeration value="GracePremium"/>
 *     &lt;enumeration value="LoanRepaymentGracePremium"/>
 *     &lt;enumeration value="ReinstatementPremium"/>
 *     &lt;enumeration value="FullyPayOffLoan"/>
 *     &lt;enumeration value="IncreaseByPercentage"/>
 *     &lt;enumeration value="DecreaseByPercentage"/>
 *     &lt;enumeration value="ProjectAutomaticIncreases"/>
 *     &lt;enumeration value="Formula"/>
 *     &lt;enumeration value="BenefitChange"/>
 *     &lt;enumeration value="LastMonthlyDeductionPremium"/>
 *     &lt;enumeration value="SolveLowestFaceToAvoidMEC"/>
 *     &lt;enumeration value="CoverageSolveBasedOnPremium"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TransactionRequestAmountRule")
@XmlEnum
public enum TransactionRequestAmountRule {

    @XmlEnumValue("CalculatedPremium")
    CALCULATED_PREMIUM("CalculatedPremium"),
    @XmlEnumValue("CurrentAmount")
    CURRENT_AMOUNT("CurrentAmount"),
    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("PercentageOfInvestment")
    PERCENTAGE_OF_INVESTMENT("PercentageOfInvestment"),
    @XmlEnumValue("SpecifiedAmount")
    SPECIFIED_AMOUNT("SpecifiedAmount"),
    @XmlEnumValue("Solve")
    SOLVE("Solve"),
    @XmlEnumValue("TargetPremium")
    TARGET_PREMIUM("TargetPremium"),
    @XmlEnumValue("SevenPayPremium")
    SEVEN_PAY_PREMIUM("SevenPayPremium"),
    @XmlEnumValue("MaximumAllowed")
    MAXIMUM_ALLOWED("MaximumAllowed"),
    @XmlEnumValue("GuidelineSinglePremium")
    GUIDELINE_SINGLE_PREMIUM("GuidelineSinglePremium"),
    @XmlEnumValue("GuidelineLevelPremium")
    GUIDELINE_LEVEL_PREMIUM("GuidelineLevelPremium"),
    @XmlEnumValue("MinimumPremium")
    MINIMUM_PREMIUM("MinimumPremium"),
    @XmlEnumValue("GracePremium")
    GRACE_PREMIUM("GracePremium"),
    @XmlEnumValue("LoanRepaymentGracePremium")
    LOAN_REPAYMENT_GRACE_PREMIUM("LoanRepaymentGracePremium"),
    @XmlEnumValue("ReinstatementPremium")
    REINSTATEMENT_PREMIUM("ReinstatementPremium"),
    @XmlEnumValue("FullyPayOffLoan")
    FULLY_PAY_OFF_LOAN("FullyPayOffLoan"),
    @XmlEnumValue("IncreaseByPercentage")
    INCREASE_BY_PERCENTAGE("IncreaseByPercentage"),
    @XmlEnumValue("DecreaseByPercentage")
    DECREASE_BY_PERCENTAGE("DecreaseByPercentage"),
    @XmlEnumValue("ProjectAutomaticIncreases")
    PROJECT_AUTOMATIC_INCREASES("ProjectAutomaticIncreases"),
    @XmlEnumValue("Formula")
    FORMULA("Formula"),
    @XmlEnumValue("BenefitChange")
    BENEFIT_CHANGE("BenefitChange"),
    @XmlEnumValue("LastMonthlyDeductionPremium")
    LAST_MONTHLY_DEDUCTION_PREMIUM("LastMonthlyDeductionPremium"),
    @XmlEnumValue("SolveLowestFaceToAvoidMEC")
    SOLVE_LOWEST_FACE_TO_AVOID_MEC("SolveLowestFaceToAvoidMEC"),
    @XmlEnumValue("CoverageSolveBasedOnPremium")
    COVERAGE_SOLVE_BASED_ON_PREMIUM("CoverageSolveBasedOnPremium");
    private final String value;

    TransactionRequestAmountRule(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransactionRequestAmountRule fromValue(String v) {
        for (TransactionRequestAmountRule c: TransactionRequestAmountRule.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
